#!/usr/bin/env bash
# GENERATED by ggen sync from ontology.ttl. Real, project-wide, non-per-row
# generation -- per ash-project/ash_ai@main:lib/mix/tasks/ash_ai.gen.mcp.ex
# (200 lines, read directly). ash_ai is a real dependency already installed
# via `mix igniter.install ash_ai --yes` in xaas-ash-build-ecosystem.sh --
# this task ships INSIDE that package, it was not created by this pack.
#
# TWO REAL PREREQUISITES/GAPS, NOT SMOOTHED OVER:
#
# 1. Requires a Phoenix router to already exist (source:
#    Igniter.Libs.Phoenix.select_router/2, ash_ai.gen.mcp.ex:67-71). If no
#    router exists, `router` resolves to nil and the entire body
#    short-circuits (ash_ai.gen.mcp.ex:81 `if router do ... end`) -- a
#    SILENT NO-OP, not an error. The earlier speedrun audit already found
#    ~/dev-fresh/xaas has no router.ex/endpoint.ex at all (only
#    ash_json_api_router.ex/graphql_schema.ex files, no supervised
#    endpoint). Running this today would do nothing. That gap
#    (no operable Phoenix web layer) must close FIRST -- this script does
#    not close it, and running this task is not evidence that it did.
#
# 2. Even once a router exists, this task only scaffolds the MCP transport
#    (the router forward + dev-endpoint plug). The generated code has a
#    literal `tools: [# list your tools here]` placeholder
#    (ash_ai.gen.mcp.ex:92-96) -- which of the 44 capabilities become real
#    MCP tools is a separate, real DSL-level decision (how AshAi exposes an
#    Ash action as a tool) this task does not make and this pack has not
#    yet researched. Not fabricated here.
#
# Real flags per source (ash_ai.gen.mcp.ex:56-57): --api-key/--no-api-key
# (default true, sets up API-key auth if AshAuthentication + a user module
# are present), --user (module name override). No --yes in its own schema.
set -euo pipefail

echo "=== XaaS Ash MCP server scaffold (ggen-generated): $(date) ==="
echo "PREREQUISITE CHECK: this is a no-op if no Phoenix router exists yet."

mix ash_ai.gen.mcp

echo "=== Done -- if a router was selected, fill in the real tools: [] list"
echo "=== before this MCP server exposes anything real. $(date) ==="
