#!/usr/bin/env bash
# xaas-ash-build.sh -- canonical, single-session Ash CLI script for the entire XaaS platform.
# Generated by an ultracode Workflow this session, grounded in:
#   - real ~/dev-fresh/xaas/deps/{ash,igniter,spark} source (this session's own Explore-agent survey)
#   - the /deep-research workflow's adversarially-verified public-docs findings (task wqgrojzmd)
#   - the real, book-verbatim Ash Framework P1.0 (Pragmatic, Le & Daniel, Aug 2025) DSL patterns
#   - all 44 real ce:Capability individuals in chatman-ecosystem/ontology/platform-console-capabilities.ttl
#
# Run this from inside a fresh Ash project (e.g. `mix igniter.new xaas --install ash --yes && cd xaas`).
# Every "mix ash.gen.*"/"mix ash.extend"/"mix igniter.*" line is a REAL, flag-verified command.
# Every "# HAND-EDIT" block marks DSL with NO generator (custom actions/policies) -- these must be
# pasted into the named resource file by hand; there is no CLI for them, confirmed from Ash's own
# source (ash.gen.change/validation/preparation only scaffold standalone modules, not inline
# resource action/policy blocks).
#
# NOT covered by this script (real, disclosed gaps, not silently assumed):
#   - AshPostgres/AshJsonApi/AshGraphql/AshAuthentication wiring (needs "mix igniter.install
#     ash_postgres ash_json_api ash_graphql ash_authentication" FIRST, then --extend postgres,json_api,graphql
#     instead of --extend ets on each resource -- this script uses the ETS data layer, which ships
#     inside ash itself, so it runs with zero extra deps and is meant as a structural proof, not a
#     production data layer choice)
#   - Ash.Policy.Authorizer's SAT-solver dependency (add {:picosat_elixir, "~> 0.2"} to mix.exs
#     BEFORE running this script if you add "authorizers: [Ash.Policy.Authorizer]" to any resource --
#     already true of ~/dev-fresh/xaas/mix.exs from earlier this session)
#   - Chapter 7 (testing) and Chapter 10 (PubSub) DSL shapes -- these did not render as text from the
#     source PDF in this session's research pass; re-verify against the book directly before adding
#     ExUnit test scaffolding or notifiers: [Ash.Notifier.PubSub] blocks

set -euo pipefail

echo "=== XaaS Ash platform build: $(date) ==="

# ===== Domain: Xaas.Operations =====

mix ash.gen.domain Xaas.Operations --yes

# ----- Resource: CastleVerbInventoryComponents (inventory-components) -----
mix ash.gen.resource Xaas.Operations.CastleVerbInventoryComponents --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/castle_verb_inventory_components.ex, inside the resource's `actions do ... end` block, add:
#
#     update :approve do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:approve) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: CastleVerbInventoryGoals (inventory-goals) -----
mix ash.gen.resource Xaas.Operations.CastleVerbInventoryGoals --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/castle_verb_inventory_goals.ex, inside the resource's `actions do ... end` block, add:
#
#     update :approve do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:approve) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: ApprovalCastleVerbSchedule (castle.verb.schedule) -----
mix ash.gen.resource Xaas.Operations.ApprovalCastleVerbSchedule --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/approval_castle_verb_schedule.ex, inside the resource's `actions do ... end` block, add:
#
#     update :schedule do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:schedule) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: ApprovalK8sFaultRemediateSuggest (k8s-fault.remediate-suggest) -----
mix ash.gen.resource Xaas.Operations.ApprovalK8sFaultRemediateSuggest --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/approval_k8s_fault_remediate_suggest.ex, inside the resource's `actions do ... end` block, add:
#
#     update :suggest do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:suggest) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: CastleVerbFortune5Requirements (fortune5-requirements) -----
mix ash.gen.resource Xaas.Operations.CastleVerbFortune5Requirements --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/castle_verb_fortune5_requirements.ex, inside the resource's `actions do ... end` block, add:
#
#     update :approve do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:approve) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: RouteCastleDeploy (route.castle.deploy) -----
mix ash.gen.resource Xaas.Operations.RouteCastleDeploy --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/route_castle_deploy.ex, inside the resource's `actions do ... end` block, add:
#
#     update :deploy do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:deploy) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: RouteCastleRun (route.castle.run) -----
mix ash.gen.resource Xaas.Operations.RouteCastleRun --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/route_castle_run.ex, inside the resource's `actions do ... end` block, add:
#
#     update :run do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:run) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: RouteCastleSchedule (route.castle.schedule) -----
mix ash.gen.resource Xaas.Operations.RouteCastleSchedule --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/route_castle_schedule.ex, inside the resource's `actions do ... end` block, add:
#
#     update :schedule do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:schedule) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

# ----- Resource: RouteCastleSunset (route.castle.sunset) -----
mix ash.gen.resource Xaas.Operations.RouteCastleSunset --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   In lib/xaas/operations/route_castle_sunset.ex, inside the resource's `actions do ... end` block, add:
#
#     update :sunset do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#
#   And add a top-level `policies do ... end` block:
#
#     policies do
#       policy action(:sunset) do
#         authorize_if actor_attribute_equals(:role, :owner)
#       end
#     end

mix compile

# ===== Domain: Xaas.Governance =====

mix ash.gen.domain Xaas.Governance --yes

# ----- ApprovalFreezeOverride (freeze.override) -----
mix ash.gen.resource Xaas.Governance.ApprovalFreezeOverride --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :override do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :overridden)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:override) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- DataDestructionCertificateIssue (data-destruction.certificate.issue) -----
mix ash.gen.resource Xaas.Governance.DataDestructionCertificateIssue --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :issue do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :issued)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:issue) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalOrgDelete (org.delete) -----
mix ash.gen.resource Xaas.Governance.ApprovalOrgDelete --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :delete do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :deleted)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:delete) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalBackupRetentionChange (backup.retention.change) -----
mix ash.gen.resource Xaas.Governance.ApprovalBackupRetentionChange --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :change do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :changed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:change) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalDrFailover (dr.failover) -----
mix ash.gen.resource Xaas.Governance.ApprovalDrFailover --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :failover do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :failed_over)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:failover) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalDsarErasure (dsar.erasure) -----
mix ash.gen.resource Xaas.Governance.ApprovalDsarErasure --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :erasure do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :erased)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:erasure) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalSsoRoleMappingUpdate (sso.role-mapping.update) -----
mix ash.gen.resource Xaas.Governance.ApprovalSsoRoleMappingUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :update do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :updated)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:update) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalExportSubscriptionUpdate (export-subscription.update) -----
mix ash.gen.resource Xaas.Governance.ApprovalExportSubscriptionUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :update do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :updated)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:update) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalEnvironmentPromote (environment.promote) -----
mix ash.gen.resource Xaas.Governance.ApprovalEnvironmentPromote --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :promote do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :promoted)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:promote) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalDeploymentQuarantine (deployment.quarantine) -----
mix ash.gen.resource Xaas.Governance.ApprovalDeploymentQuarantine --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :quarantine do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :quarantined)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:quarantine) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalComplianceRotationBlock (compliance.rotation-block) -----
mix ash.gen.resource Xaas.Governance.ApprovalComplianceRotationBlock --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :block do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :blocked)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:block) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalBreakGlassJustificationReview (break-glass.justification-review) -----
mix ash.gen.resource Xaas.Governance.ApprovalBreakGlassJustificationReview --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :review do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :reviewed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:review) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalSubprocessorRegistryUpdate (subprocessor.registry.update) -----
mix ash.gen.resource Xaas.Governance.ApprovalSubprocessorRegistryUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :update do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :updated)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:update) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalLeRequestRespond (le-request.respond) -----
mix ash.gen.resource Xaas.Governance.ApprovalLeRequestRespond --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :respond do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :responded)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:respond) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalDeniedPartyOverride (denied-party.override) -----
mix ash.gen.resource Xaas.Governance.ApprovalDeniedPartyOverride --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :override do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :overridden)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:override) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalChangeOfControlNotify (change-of-control.notify) -----
mix ash.gen.resource Xaas.Governance.ApprovalChangeOfControlNotify --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :notify do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :notified)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:notify) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalInsurancePolicyUpdate (insurance.policy.update) -----
mix ash.gen.resource Xaas.Governance.ApprovalInsurancePolicyUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :update do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :updated)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:update) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalPersonnelAttestationRecord (personnel.attestation.record) -----
mix ash.gen.resource Xaas.Governance.ApprovalPersonnelAttestationRecord --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :record do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :recorded)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:record) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalSourceEscrowSnapshot (source-escrow.snapshot) -----
mix ash.gen.resource Xaas.Governance.ApprovalSourceEscrowSnapshot --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :snapshot do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :snapshotted)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:snapshot) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalPentestFindingResolve (pentest.finding.resolve) -----
mix ash.gen.resource Xaas.Governance.ApprovalPentestFindingResolve --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :resolve do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :resolved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:resolve) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalCmekKeyBinding (cmek.key-binding) -----
mix ash.gen.resource Xaas.Governance.ApprovalCmekKeyBinding --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :bind do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :bound)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:bind) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalVendorOffboardingAttestationIssue (vendor-offboarding.attestation.issue) -----
mix ash.gen.resource Xaas.Governance.ApprovalVendorOffboardingAttestationIssue --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :issue do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :issued)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:issue) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalLegalHoldRelease (legal-hold.release) -----
mix ash.gen.resource Xaas.Governance.ApprovalLegalHoldRelease --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :release do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :released)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:release) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- ApprovalGeofenceExceptionGrant (geofence.exception.grant) -----
mix ash.gen.resource Xaas.Governance.ApprovalGeofenceExceptionGrant --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes
# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :grant do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :granted)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:grant) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

mix compile

# ===== Domain: Xaas.Billing =====

mix ash.gen.domain Xaas.Billing --yes

# ----- Resource: ApprovalQuotaOverride (capability: quota.override) -----
mix ash.gen.resource Xaas.Billing.ApprovalQuotaOverride --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :override do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :overridden)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:override) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: ApprovalTierDowngrade (capability: tier.downgrade) -----
mix ash.gen.resource Xaas.Billing.ApprovalTierDowngrade --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :downgrade do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :downgraded)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:downgrade) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: ApprovalSlaCreditApply (capability: sla.credit.apply) -----
mix ash.gen.resource Xaas.Billing.ApprovalSlaCreditApply --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :apply do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :applied)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:apply) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: ApprovalPricingOverride (capability: pricing.override) -----
mix ash.gen.resource Xaas.Billing.ApprovalPricingOverride --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :override do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :overridden)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:override) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: ApprovalPatchSlaCreditApply (capability: patch-sla.credit.apply) -----
mix ash.gen.resource Xaas.Billing.ApprovalPatchSlaCreditApply --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :apply do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :applied)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:apply) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: ApprovalInvoiceReconciliationApprove (capability: invoice.reconciliation.approve) -----
mix ash.gen.resource Xaas.Billing.ApprovalInvoiceReconciliationApprove --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
#   actions do
#     defaults [:read]
#     update :approve do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :approved)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#   policies do
#     policy action(:approve) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

mix compile

# ===== Domain: Xaas.Platform =====

mix ash.gen.domain Xaas.Platform --yes

# ----- Resource: RouteFeatureFlags (capability: route.feature-flags) -----
mix ash.gen.resource Xaas.Platform.RouteFeatureFlags --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
# In lib/xaas/platform/route_feature_flags.ex, inside the resource's `actions do ... end` block, add:
#
#   actions do
#     defaults [:read]
#     update :route do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :routed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#
#   policies do
#     policy action(:route) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: RouteOrgsCustomDomain (capability: route.orgs.custom-domain) -----
mix ash.gen.resource Xaas.Platform.RouteOrgsCustomDomain --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
# In lib/xaas/platform/route_orgs_custom_domain.ex, inside the resource's `actions do ... end` block, add:
#
#   actions do
#     defaults [:read]
#     update :route do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :routed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#
#   policies do
#     policy action(:route) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: RouteProjects (capability: route.projects) -----
mix ash.gen.resource Xaas.Platform.RouteProjects --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
# In lib/xaas/platform/route_projects.ex, inside the resource's `actions do ... end` block, add:
#
#   actions do
#     defaults [:read]
#     update :route do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :routed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#
#   policies do
#     policy action(:route) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: RouteProjectsBackups (capability: route.projects.backups) -----
mix ash.gen.resource Xaas.Platform.RouteProjectsBackups --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
# In lib/xaas/platform/route_projects_backups.ex, inside the resource's `actions do ... end` block, add:
#
#   actions do
#     defaults [:read]
#     update :route do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :routed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#
#   policies do
#     policy action(:route) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

# ----- Resource: RouteSecrets (capability: route.secrets) -----
mix ash.gen.resource Xaas.Platform.RouteSecrets --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

# HAND-EDIT (no generator exists for this):
# In lib/xaas/platform/route_secrets.ex, inside the resource's `actions do ... end` block, add:
#
#   actions do
#     defaults [:read]
#     update :route do
#       accept []
#       argument :approved_by, :string, allow_nil?: false
#       change set_attribute(:status, :routed)
#       change set_attribute(:approved_by, arg(:approved_by))
#     end
#   end
#
#   policies do
#     policy action(:route) do
#       authorize_if actor_attribute_equals(:role, :owner)
#     end
#   end

mix compile

echo "=== Build complete: $(date) ==="
echo "Run 'mix ash.generate_resource_diagrams' (requires local Mermaid CLI) to visualize the result."
echo "Real gaps NOT covered by this script, see header comment: AshPostgres/AshJsonApi/AshGraphql/AshAuthentication wiring, testing (Ch7)/PubSub (Ch10) DSL, SAT-solver dep for any resource adding Ash.Policy.Authorizer."
