#!/usr/bin/env bash
# GENERATED by ggen sync from ontology.ttl + queries/render-targets.rq --
# do not hand-edit, regenerate instead. Real mix ash.gen.resource lines,
# one per real ce:Capability individual (see ontology.ttl's xar:RenderTarget
# individuals and their real xar:renderOf pcc: IRI).
#
# v0.3.0 change (source-grounded against ash-project/ash@main:lib/mix/tasks/gen/
# ash.gen.resource.ex, all 804 lines read directly):
#
# 1. --default-actions now includes create,update (not just read) -- per
#    source this generates a REAL accept-list from `public`-flagged
#    attributes (default_accept, ash.gen.resource.ex:167-182,605-622), not a
#    stub. requested_by/approved_by are marked `public` so they're actually
#    acceptable on create/update.
#
# 2. Structural differentiation, not cosmetic: the CLI has no flag to set an
#    attribute's *value* (no --default), only its name/type/modifiers -- so
#    per-capability differentiation has to be structural. The real
#    xar:reversible fact (copied from ce:reversible in
#    platform-console-capabilities.ttl) drives a genuine schema difference:
#    the 9 real irreversible capabilities get an extra
#    verification_required:boolean:required attribute the other 35 don't,
#    matching what the ontology itself asserts about them (e.g.
#    data-destruction.certificate.issue's real fail-closed,
#    verification-gated semantics) instead of producing 44 byte-identical
#    shells regardless of what each capability claims to do.
#
# STILL A SCAFFOLD, NOT A GAP HIDDEN: mix ash.gen.resource has no code path
# for custom action bodies or `policies do` blocks (confirmed absent from its
# entire source) -- authorization and the actual verification/business logic
# remain a separate, explicitly-labeled hand-authoring pass, not something
# this template can or should synthesize from an ontology description string.
set -euo pipefail

echo "=== XaaS Ash resources (ggen-generated): $(date) ==="


mix ash.gen.resource Xaas.Billing.ApprovalInvoiceReconciliationApprove --domain Xaas.Billing --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalPatchSlaCreditApply --domain Xaas.Billing --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalPricingOverride --domain Xaas.Billing --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalQuotaOverride --domain Xaas.Billing --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalSlaCreditApply --domain Xaas.Billing --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalTierDowngrade --domain Xaas.Billing --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalBackupRetentionChange --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalBreakGlassJustificationReview --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalChangeOfControlNotify --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalCmekKeyBinding --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalComplianceRotationBlock --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDeniedPartyOverride --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDeploymentQuarantine --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDrFailover --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDsarErasure --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalEnvironmentPromote --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalExportSubscriptionUpdate --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalFreezeOverride --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalGeofenceExceptionGrant --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalInsurancePolicyUpdate --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalLeRequestRespond --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalLegalHoldRelease --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalOrgDelete --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalPentestFindingResolve --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalPersonnelAttestationRecord --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalSourceEscrowSnapshot --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalSsoRoleMappingUpdate --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalSubprocessorRegistryUpdate --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalVendorOffboardingAttestationIssue --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Governance.DataDestructionCertificateIssue --domain Xaas.Governance --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.ApprovalCastleVerbSchedule --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.ApprovalK8sFaultRemediateSuggest --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.CastleVerbFortune5Requirements --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.CastleVerbInventoryComponents --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.CastleVerbInventoryGoals --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleDeploy --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleRun --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleSchedule --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleSunset --domain Xaas.Operations --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteFeatureFlags --domain Xaas.Platform --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteOrgsCustomDomain --domain Xaas.Platform --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteProjects --domain Xaas.Platform --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteProjectsBackups --domain Xaas.Platform --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteSecrets --domain Xaas.Platform --default-actions read,create,update --uuid-primary-key id --attribute requested_by:string:required:public --attribute approved_by:string:public --attribute verification_required:boolean:required:public --extend ets --yes


mix compile
echo "=== Done: $(date) ==="
