#!/usr/bin/env bash
# GENERATED by ggen sync from packages.ttl + queries/package-selection.rq.
#
# Real catalog rendering, not a hand-maintained fixed list -- per the session's
# "80/20 ggen wrapper" architecture: this file is ONE real instantiation of
# whatever a deployment's ontology selects from the full 131-package real
# catalog (packages.ttl). A different deployment's own ggen.toml would render
# a different subset from the same underlying catalog + query, driven by that
# deployment's own real ce:Capability domain facts (a real, disclosed
# follow-up -- domain-affinity facts per package aren't encoded yet, so today
# every catalogStatus="include" package renders here unconditionally).
#
# Packages already reflected in the hand-assembled xaas-ash-build-ecosystem.sh
# are marked as such (xar:alreadyInstalled) and sorted first -- this script is
# NOT yet a drop-in replacement for that file (their install ordering/flags/
# --auth-strategy selections/HAND-EDIT notes encode real judgment this
# catalog-only rendering doesn't have) -- it demonstrates the real catalog
# mechanism and is meant to be diffed against xaas-ash-build-ecosystem.sh,
# not silently substituted for it.
set -euo pipefail

echo "=== XaaS real package catalog (ggen-generated): $(date) ==="
echo "=== 131 real packages selected from the 131-entry catalog ==="


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here


# already in xaas-ash-build-ecosystem.sh -- shown for catalog completeness, not re-installed here



# real org: ash-project (not independently re-verified this session) -- OpenSearch data layer for the Ash Framework (implements AepfOpensearch.DataLayer)
mix igniter.install aepf_opensearch --yes



# real org: ash-project (not independently re-verified this session) -- Ash Live Vue Adapter (Alva) connects Ash Framework resources seamlessly to Phoenix LiveView and Vue 3 with end-to-end TypeScript code generation.
mix igniter.install alva --yes



# real org: ash-project (not independently re-verified this session) -- Ash Framework DataLayer for Apache AGE graph database
mix igniter.install ash_age --yes



# real org: bradleygolden -- An Ash Framework extension for building AI agent applications with LLM integration.
mix igniter.install ash_agent --yes



# real org: bradleygolden -- Session persistence extension for AshAgent.
mix igniter.install ash_agent_session --yes



# real org: bradleygolden -- Provider-agnostic tool calling runtime and adapters for Ash Agent.
mix igniter.install ash_agent_tools --yes



# real org: ash-project (not independently re-verified this session) -- The AppSignal APM integration for Ash Framework
mix igniter.install ash_appsignal --yes



# real org: ash-project (not independently re-verified this session) -- Ash Framework DataLayer for ArcadeDB — native OpenCypher over the HTTP command API.
mix igniter.install ash_arcadic --yes



# real org: ash-project (not independently re-verified this session) -- ATProto utilities for the Ash Framework.
mix igniter.install ash_atproto --yes



# real org: ash-project (not independently re-verified this session) -- Swedish BankID authentication strategy for Ash Authentication
mix igniter.install ash_authentication_bankid --yes



# real org: ash-project (not independently re-verified this session) -- An OAuth 2.1 authorization server for Ash Framework apps — RFC 7591 dynamic client registration, PKCE, audience-bound JWTs, refresh-token rotation, and a built-
mix igniter.install ash_authentication_oauth2_server --yes



# real org: ash-project (not independently re-verified this session) -- Automatically generates code_interface for ash resources' actions
mix igniter.install ash_auto_code_interface --yes



# real org: ash-project (not independently re-verified this session) -- Integration library between Ash Framework and Backpex admin interface (early development). Provides a DSL for creating admin interfaces for Ash resources.
mix igniter.install ash_backpex --yes



# real org: ash-project (not independently re-verified this session) -- Ash integration for BAML (Boundary ML) functions, enabling type-safe LLM interactions
mix igniter.install ash_baml --yes



# real org: ash-project (not independently re-verified this session) -- Generate identity, get_by/list_by actions and code_interface for unique keys.
mix igniter.install ash_canonical_identity --yes



# real org: ash-project (not independently re-verified this session) -- An integration between Ash and Carbonite.
mix igniter.install ash_carbonite --yes



# real org: ash-project (not independently re-verified this session) -- Automatically sets `archive_related` from `ash_archival` for all fully-contained child relationships.
mix igniter.install ash_cascade_archival --yes



# real org: ash-project (not independently re-verified this session) -- An extension for Ash.Resource which adds the ability to wrap actions in circuit breakers to allow for graceful handling of and recovery from failures.
mix igniter.install ash_circuit_breaker --yes



# real org: ash-project (not independently re-verified this session) -- An Ash Framework data layer for ClickHouse
mix igniter.install ash_clickhouse --yes



# real org: ash-project (not independently re-verified this session) -- CQRS pattern implementation for Ash Framework resources using Commanded
mix igniter.install ash_commanded --yes



# real org: ash-project (not independently re-verified this session) -- GDPR-compliant cookie consent management for Ash Framework applications. Provides Phoenix Components, LiveView integration, and database persistence for trackin
mix igniter.install ash_cookie_consent --yes



# real org: ash-project (not independently re-verified this session) -- The CSV data layer for Ash Framework
mix igniter.install ash_csv --yes



# real org: ash-project (not independently re-verified this session) -- A CubDB data layer for `Ash` resources.
mix igniter.install ash_cubdb --yes



# real org: ash-project (not independently re-verified this session) -- Configure a default sort to apply when a read action or a has_many relationship has no sort.
mix igniter.install ash_default_sort --yes



# real org: team-alembic -- AshDiagram is a library for generating beautiful, interactive diagrams to visualize your Ash Framework applications.
mix igniter.install ash_diagram --yes



# real org: ash-project (not independently re-verified this session) -- Event-driven notification system for Ash Framework with multiple transport types
mix igniter.install ash_dispatch --yes



# real org: ash-project (not independently re-verified this session) -- Declarative, DSL-driven analytics for Ash resources (frequency, aggregate, time_bucket, percentile, histogram).
mix igniter.install ash_dyan --yes



# real org: ash-project (not independently re-verified this session) -- DynamoDB data layer for `Ash` resources.
mix igniter.install ash_dynamo --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension for automatic event logging and audit trails on resources.
mix igniter.install ash_event_log --yes



# real org: ash-project (not independently re-verified this session) -- Encrypted integer IDs for Ash resources using Feistel cipher
mix igniter.install ash_feistel_cipher --yes



# real org: ash-project (not independently re-verified this session) -- AshFormBuilder = AshPhoenix.Form + Auto UI + Smart Components + Themes. Declarative form engine for Ash Framework with zero-config field inference, searchable/
mix igniter.install ash_form_builder --yes



# real org: ash-project (not independently re-verified this session) -- Tools for using Geo, Topo and PostGIS with Ash
mix igniter.install ash_geo --yes



# real org: ash-project (not independently re-verified this session) -- Generate type-safe Gleam clients directly from your Ash resources and actions, ensuring end-to-end type safety between Gleam and Elixir.
mix igniter.install ash_gleam --yes



# real org: ash-project (not independently re-verified this session) -- Permission-based authorization extension for Ash Framework
mix igniter.install ash_grant --yes



# real org: ash-project (not independently re-verified this session) -- Ash Haikuify is an Ash Framework extension that slugifys resources in haiku style
mix igniter.install ash_haikuify --yes



# real org: ash-project (not independently re-verified this session) -- Shared core library for Ash interoperability with multiple languages. Provides type introspection, discovery, and RPC pipeline utilities.
mix igniter.install ash_introspection --yes



# real org: ash-project (not independently re-verified this session) -- Ash extension for implementing Jason protocol
mix igniter.install ash_jason --yes



# real org: ash-project (not independently re-verified this session) -- Integration between the Ash Framework and the Jido Agent ecosystem.
mix igniter.install ash_jido --yes



# real org: ash-project (not independently re-verified this session) -- Generate type-safe Kotlin Multiplatform clients directly from your Ash resources and actions, ensuring end-to-end type safety between your backend and frontend.
mix igniter.install ash_kotlin_multiplatform --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension for embedding Lua scripts with a consistent actor, tenant, and context.
mix igniter.install ash_lua --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension that brings full-text search to your resources via Meilisearch.
mix igniter.install ash_meilisearch --yes



# real org: ash-project (not independently re-verified this session) -- A mock resource generator extension for Ash resources.
mix igniter.install ash_mock --yes



# real org: ash-project (not independently re-verified this session) -- Multi-account linking and switching for Ash apps
mix igniter.install ash_multi_account --yes



# real org: ash-project (not independently re-verified this session) -- Ash DataLayer for Neo4j
mix igniter.install ash_neo4j --yes



# real org: ash-project (not independently re-verified this session) -- OpenAPI 3.0 and 3.1 spec generator for Ash Framework resources. Supports dual-version output for migration scenarios.
mix igniter.install ash_oaskit --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension to use object IDs as primary and foreign keys.
mix igniter.install ash_object_ids --yes



# real org: ash-project (not independently re-verified this session) -- Ash extension for OpenFeed (Australian CDR banking and energy data). Stores disclosure grants and their tokens on your own Ash resource.
mix igniter.install ash_openfeed --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension which generates mix tasks for Ash actions
mix igniter.install ash_ops --yes



# real org: ash-project (not independently re-verified this session) -- Ash Extension for implementing Outstanding Protocol
mix igniter.install ash_outstanding --yes



# real org: ash-project (not independently re-verified this session) -- Adds full-text search, scoping, filtering, ordering, and pagination APIs for the Ash Framework.
mix igniter.install ash_pagify --yes



# real org: ash-project (not independently re-verified this session) -- A flexible, composable resource management UI library for Ash Framework applications. Features automatic resource introspection, AshComputer-powered reactive st
mix igniter.install ash_panel --yes



# real org: ash-project (not independently re-verified this session) -- AshPaperTrail extension that lifts action context onto a version's metadata and enqueues an Oban job when the version is created.
mix igniter.install ash_paper_plane --yes



# real org: ash-project (not independently re-verified this session) -- Ash adapter for Parc: one declared authorization policy, gating writes and row-scoping reads across every resource.
mix igniter.install ash_parc --yes



# real org: ash-project (not independently re-verified this session) -- Ash Parental is an Ash Framework extension that brings STI(Single Table Inheritance) capability to your resource
mix igniter.install ash_parental --yes



# real org: ash-project (not independently re-verified this session) -- Utilities for integrating Ash and Phoenix
mix igniter.install ash_phoenix --yes



# real org: ash-project (not independently re-verified this session) -- Ash extension for generating function configurations for PhoenixGenApi framework from Ash resources.
mix igniter.install ash_phoenix_gen_api --yes



# real org: ash-project (not independently re-verified this session) -- A powerful Ash Framework extension for handling translations in Phoenix applications with policy-aware, multi-backend support
mix igniter.install ash_phoenix_translations --yes



# real org: ash-project (not independently re-verified this session) -- Automatically adds AshPostgres custom indexes for `belongs_to` relationships in Ash resources.
mix igniter.install ash_postgres_belongs_to_index --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension to use prefixed IDs as primary and foreign keys.
mix igniter.install ash_prefixed_id --yes



# real org: ash-project (not independently re-verified this session) -- Performance profiling and optimization toolkit for Ash Framework applications. Analyze DSL complexity, identify compilation bottlenecks, and get actionable opti
mix igniter.install ash_profiler --yes



# real org: ash-project (not independently re-verified this session) -- Declarative UI for Ash Framework.
mix igniter.install ash_pyro --yes



# real org: ash-project (not independently re-verified this session) -- Automatically render UI for Ash resources via DSL configuration.
mix igniter.install ash_pyro_components --yes



# real org: ash-project (not independently re-verified this session) -- A simple query builder helper for Ash.Query
mix igniter.install ash_query_builder --yes



# real org: ash-project (not independently re-verified this session) -- Random parameter generation for Ash resources.
mix igniter.install ash_random_params --yes



# real org: traveltechdeluxe -- A small extension for easier application of policies
mix igniter.install ash_rbac --yes



# real org: ash-project (not independently re-verified this session) -- An Ash-native Replicant.Sink adapter: effect-once CDC mirroring into AshPostgres resources.
mix igniter.install ash_replicant --yes



# real org: ash-project (not independently re-verified this session) -- Shortcut DSL for attributes and relationships in Ash resources.
mix igniter.install ash_req_opt --yes



# real org: ash-project (not independently re-verified this session) -- ⚠️ EXPERIMENTAL: Expose Ash Resource actions over tRPC with Plug-compatible router/controller and tooling. Breaking changes may occur frequently.
mix igniter.install ash_rpc --yes



# real org: ash-project (not independently re-verified this session) -- Ash DataLayer for the Sanity.io CMS
mix igniter.install ash_sanity --yes



# real org: ash-project (not independently re-verified this session) -- Reusable test data generation for Ash applications with dependency resolution and scenario composition.
mix igniter.install ash_scenario --yes



# real org: ash-project (not independently re-verified this session) -- An Ash Framework data layer for ScyllaDB/Apache Cassandra using Xandra
mix igniter.install ash_scylla --yes



# real org: ash-project (not independently re-verified this session) -- Server-Driven UI for Phoenix LiveView applications backed by Ash resources.
mix igniter.install ash_sdui --yes



# real org: ash-project (not independently re-verified this session) -- Ash extension for generating sitemaps
mix igniter.install ash_sitemap --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension for slugifying attributes of a resource.
mix igniter.install ash_slug --yes



# real org: ash-project (not independently re-verified this session) -- Sqids type for Ash framework
mix igniter.install ash_sqids --yes



# real org: ash-project (not independently re-verified this session) -- Shared utilities for ecto-based sql data layers.
mix igniter.install ash_sql --yes



# real org: ash-project (not independently re-verified this session) -- The SQLite data layer for Ash Framework.
mix igniter.install ash_sqlite --yes



# real org: ash-project (not independently re-verified this session) -- A DSL for defining custom Ash types that behave like algebraic sum types.
mix igniter.install ash_sum_type --yes



# real org: ash-project (not independently re-verified this session) -- A sortable, paginated table as a LiveView component, that integrates with Ash
mix igniter.install ash_table --yes



# real org: ash-project (not independently re-verified this session) -- Thrift extension for the Ash framework.
mix igniter.install ash_thrift --yes



# real org: ash-project (not independently re-verified this session) -- Ash extension for implementing ToonEx.Encoder protocol
mix igniter.install ash_toon_ex --yes



# real org: ash-project (not independently re-verified this session) -- An Ash extension for managing translations on a resource.
mix igniter.install ash_translation --yes



# real org: ash-project (not independently re-verified this session) -- Terminal-based interactive explorer for Ash Framework applications
mix igniter.install ash_tui --yes



# real org: ash-project (not independently re-verified this session) -- Generate type-safe TypeScript clients directly from your Ash resources and actions, ensuring end-to-end type safety between your backend and frontend.
mix igniter.install ash_typescript --yes



# real org: ash-project (not independently re-verified this session) -- Precompiled NIFs and tooling to render Typst documents.
mix igniter.install ash_typst --yes



# real org: ash-project (not independently re-verified this session) -- ULID type for Ash framework
mix igniter.install ash_ulid --yes



# real org: ash-project (not independently re-verified this session) -- Tools for using UUID based id with Ash
mix igniter.install ash_uuid --yes



# real org: ash-project (not independently re-verified this session) -- Tools for using UUIDv7 id with Ash
mix igniter.install ash_uuid_v7 --yes



# real org: ash-project (not independently re-verified this session) -- A metric weight Ash.Type. Stored canonically as integer milligrams, with ergonomic conversions to grams and kilograms.
mix igniter.install ash_weight --yes



# real org: ash-project (not independently re-verified this session) -- Bridge Ash types and resources to Zoi validation schemas
mix igniter.install ash_zoi --yes



# real org: ash-project (not independently re-verified this session) -- Low code UI for the elixir's Phoenix Framework
mix igniter.install aurora_uix --yes



# real org: ash-project (not independently re-verified this session) -- A powerful, intelligent data table component for Phoenix LiveView applications with seamless Ash Framework integration.
mix igniter.install cinder --yes



# real org: team-alembic -- Clarity is an interactive introspection and visualization tool for Elixir projects, providing navigable graphs and diagrams for frameworks like Ash, Phoenix, an
mix igniter.install clarity --yes



# real org: ash-project (not independently re-verified this session) -- TMF Service and Resource Manager with a difference
mix igniter.install diffo --yes



# real org: ash-project (not independently re-verified this session) -- Parse, validate, and evaluate mathematical and logical expressions with variables, functions, and optional Ash integration.
mix igniter.install elex --yes



# real org: ash-project (not independently re-verified this session) -- Meta-framework for governance, observability, and AI integration with Ash
mix igniter.install foundry_stack --yes



# real org: ash-project (not independently re-verified this session) -- A keyboard-driven LiveView console to probe your Ash resources — zero UI code.
mix igniter.install green_ash --yes



# real org: ash-project (not independently re-verified this session) -- Elixir client, Plug and error_logger for integrating with the Honeybadger.io exception tracker"
mix igniter.install honeybadger --yes



# real org: ash-project (not independently re-verified this session) -- Converts an abstract schema into JSON schemas required by various AI providers, minimizing code changes when switching providers.
mix igniter.install lang_schema --yes



# real org: ash-project (not independently re-verified this session) -- Declarative state management for Phoenix LiveView, built for Ash Framework
mix igniter.install lavash --yes



# real org: ash-project (not independently re-verified this session) -- List helpers used in other upcoming packages under mavuio/*
mix igniter.install mavu_list --yes



# real org: ash-project (not independently re-verified this session) -- Mishka Gervaz is a comprehensive, declarative UI library for the Ash ecosystem — define tables, forms, and data-driven interfaces entirely through DSL, with bui
mix igniter.install mishka_gervaz --yes



# real org: ash-project (not independently re-verified this session) -- Resource-driven Mob screens from Ash: declare Ash resources, get list/detail/create screens on device
mix igniter.install mob_ash --yes



# real org: ash-project (not independently re-verified this session) -- A spec-compliant Open Responses server for Elixir and Phoenix, with pluggable provider adapters and first-class streaming.
mix igniter.install open_responses --yes



# real org: ash-project (not independently re-verified this session) -- An Elixir library for building AI coding agents, OTP-native with tool system, extensions, and session persistence.
mix igniter.install pi_ex_native --yes



# real org: ash-project (not independently re-verified this session) -- Reactive DAG engine as an Ash extension: dirty frontier, depth-ordered incremental drain, change propagation. Author nodes as Ash resources with reduce/join/agg
mix igniter.install reactive_dag --yes



# real org: ash-project (not independently re-verified this session) -- A hybrid form engine for Phoenix LiveView + Ash that lets you combine form-as-data, form-as-code, and mixed mode
mix igniter.install runes --yes



# real org: ash-project (not independently re-verified this session) -- Ash extension for multilingual full-text search: a `search do … end` DSL that auto-generates the tsvector index, keeps a stemmed column in sync, and exposes a t
mix igniter.install search_ash --yes



# real org: ash-project (not independently re-verified this session) -- Test factories for Ash resources.
mix igniter.install smokestack --yes



# real org: ash-project (not independently re-verified this session) -- Spark DSL walker and introspection library.
mix igniter.install spark_meta --yes



# real org: ash-project (not independently re-verified this session) -- A struct and functions for working with Valve's SteamID format.
mix igniter.install steamid --yes



# real org: ash-project (not independently re-verified this session) -- A reusable chart library for Ash Framework applications with Phoenix LiveView integration.
mix igniter.install tapir --yes



echo "=== Done: $(date) ==="
