#!/usr/bin/env bash
# GENERATED by ggen sync from ontology.ttl + queries/render-targets.rq --
# do not hand-edit, regenerate instead. Real mix ash.gen.resource lines,
# one per real ce:Capability individual (see ontology.ttl's xar:RenderTarget
# individuals and their real xar:renderOf pcc: IRI).
set -euo pipefail

echo "=== XaaS Ash resources (ggen-generated): $(date) ==="


mix ash.gen.resource Xaas.Billing.ApprovalInvoiceReconciliationApprove --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalPatchSlaCreditApply --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalPricingOverride --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalQuotaOverride --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalSlaCreditApply --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Billing.ApprovalTierDowngrade --domain Xaas.Billing --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalBackupRetentionChange --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalBreakGlassJustificationReview --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalChangeOfControlNotify --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalCmekKeyBinding --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalComplianceRotationBlock --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDeniedPartyOverride --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDeploymentQuarantine --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDrFailover --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalDsarErasure --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalEnvironmentPromote --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalExportSubscriptionUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalFreezeOverride --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalGeofenceExceptionGrant --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalInsurancePolicyUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalLeRequestRespond --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalLegalHoldRelease --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalOrgDelete --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalPentestFindingResolve --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalPersonnelAttestationRecord --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalSourceEscrowSnapshot --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalSsoRoleMappingUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalSubprocessorRegistryUpdate --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.ApprovalVendorOffboardingAttestationIssue --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Governance.DataDestructionCertificateIssue --domain Xaas.Governance --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.ApprovalCastleVerbSchedule --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.ApprovalK8sFaultRemediateSuggest --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.CastleVerbFortune5Requirements --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.CastleVerbInventoryComponents --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.CastleVerbInventoryGoals --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleDeploy --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleRun --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleSchedule --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Operations.RouteCastleSunset --domain Xaas.Operations --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteFeatureFlags --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteOrgsCustomDomain --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteProjects --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteProjectsBackups --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes

mix ash.gen.resource Xaas.Platform.RouteSecrets --domain Xaas.Platform --default-actions read --uuid-primary-key id --attribute requested_by:string:required --attribute approved_by:string --extend ets --yes


mix compile
echo "=== Done: $(date) ==="
