#!/usr/bin/env bash
# GENERATED by ggen sync from ontology.ttl. Real, structural, one-time
# generation -- per ash-project/ash@main:lib/mix/tasks/gen/
# ash.gen.base_resource.ex (read directly, 110 lines): this task generates a
# `__using__` macro AND rewrites every existing `use Ash.Resource` call site
# project-wide via Igniter.update_all_elixir_files/2
# (ash.gen.base_resource.ex:59-80). Must run BEFORE the 44 resources in
# xaas-ash-build-base-GENERATED.sh so they use Xaas.Resource --base from the
# start (matches the ordering the prior hand-assembled build used).
#
# This is the single highest-leverage lever confirmed in the real ash.gen.*
# surface: a cross-cutting concern added ONCE to Xaas.Resource's __using__
# macro (e.g. a shared capability-IRI attribute, or a receipt/audit hook)
# propagates to all 44 resources via this rewrite mechanism, instead of
# requiring 44 separate hand-edits. That hand-edit to Xaas.Resource itself is
# explicitly NOT ggen's job -- it is real business logic (what a receipt hook
# actually does), the same class of thing ash.gen.change/validation/
# preparation can only stub, and belongs in a labeled, separate
# hand-authoring pass, not synthesized here.
set -euo pipefail

echo "=== XaaS Ash base resource (ggen-generated): $(date) ==="

mix ash.gen.base_resource Xaas.Resource --yes

echo "=== Xaas.Resource generated. REQUIRED NEXT STEP (hand-authored, not"
echo "=== ggen's job): add real shared attributes/behavior to its __using__"
echo "=== macro in lib/xaas/resource.ex before generating the 44 resources."
echo "=== Currently a bare passthrough (use Ash.Resource, unquote(opts)) --"
echo "=== confirmed empty in the prior speedrun's audit."
echo "=== Done: $(date) ==="
