#!/usr/bin/env python3
"""Project gate 020 (gates/020_applicability_public_class_only.rq).

Gate 020 admits a strategic condition only over a class that is actually
declared (rdf:type owl:Class or rdfs:Class) in one of the vendored public
vocabularies (W3C ORG, PROV-O, schema.org, SOSA, SSN, OWL-Time) or in this
pack's own vocabulary (ontology.ttl, ontology/world-model.ttl), and whose IRI
lies in the namespace that source owns. A namespace prefix alone is not
enough: http://www.w3.org/ns/org#PrivateRivalLedger is refused because ORG
does not declare it.

The admitted class list is embedded in the query itself (a NOT IN list), not
read from the data graph, so data under judgement can never admit its own
class by declaring it. This also keeps the gate a single-default-graph query:
ggen-engine refuses SPARQL GRAPH clauses (FM-GRAPH-008), so a named-graph
registry is not an option.

The gate file is a PROJECTION of those inputs and is never edited by hand.

Usage:
    python3 scripts/project_public_classes.py            # rewrite the gate
    python3 scripts/project_public_classes.py --stdout   # print the projection
    python3 scripts/project_public_classes.py --check    # exit 1 if stale

Determinism: the class list is sorted by IRI; the header lists each input
with its sha256, so an input change without a re-projection is detected by
--check.

Authority: NONE. The projection selects; it never actuates.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from rdflib import Graph, URIRef
from rdflib.namespace import OWL, RDF, RDFS

PACK_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = PACK_ROOT / "gates" / "020_applicability_public_class_only.rq"
SD = "https://ggen.dev/ontology/strategic-doctrine#"
SCHEMA = "ggen.strategic-doctrine-public-class-gate/1"

# input file -> namespaces a class from that file must lie in
INPUTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("ontology.ttl", (SD,)),
    ("ontology/world-model.ttl", (SD,)),
    ("sources/vendor/org/source.ttl", ("http://www.w3.org/ns/org#",)),
    ("sources/vendor/owl-time/source.ttl", ("http://www.w3.org/2006/time#",)),
    ("sources/vendor/prov-o/source.ttl", ("http://www.w3.org/ns/prov#",)),
    ("sources/vendor/schema-org/source.ttl", ("https://schema.org/", "http://schema.org/")),
    ("sources/vendor/sosa/source.ttl", ("http://www.w3.org/ns/sosa/",)),
    ("sources/vendor/ssn/source.ttl", ("http://www.w3.org/ns/ssn/",)),
)


def admitted_classes() -> list[str]:
    classes: set[str] = set()
    for relative, namespaces in INPUTS:
        graph = Graph()
        graph.parse(PACK_ROOT / relative, format="turtle")
        for meta in (OWL.Class, RDFS.Class):
            for subject in graph.subjects(RDF.type, meta):
                if isinstance(subject, URIRef) and str(subject).startswith(namespaces):
                    classes.add(str(subject))
    return sorted(classes)


def render() -> str:
    lines = [
        "# MESSAGE: a strategic condition is evaluated only over instances of a class",
        "# that is actually declared in a vendored public vocabulary (W3C ORG, PROV-O,",
        "# schema.org, SOSA/SSN, OWL-Time) or in this pack's own vocabulary. A",
        "# namespace prefix alone is not enough: a made-up class under a W3C namespace",
        "# (e.g. org:PrivateRivalLedger) is refused just like a private class. A",
        "# condition with no class at all is refused too.",
        "#",
        "# The admitted class list below is embedded in the query, so data under",
        "# judgement cannot admit its own class by declaring it.",
        "#",
        "# Each row names the offending condition, its class, and the reason.",
        "#",
        f"# schema: {SCHEMA}",
        "# GENERATED by scripts/project_public_classes.py -- never edit by hand.",
        "# authority: NONE (ceiling SELECT/CONSTRUCT)",
    ]
    for relative, _ in INPUTS:
        digest = hashlib.sha256((PACK_ROOT / relative).read_bytes()).hexdigest()
        lines.append(f"# input {relative} sha256:{digest}")
    classes = admitted_classes()
    lines.append(f"# admitted classes: {len(classes)}")
    namespaces = sorted({ns for _, spaces in INPUTS for ns in spaces})
    ns_test = " ||\n".join(f'      STRSTARTS(STR(?class), "{ns}")' for ns in namespaces)
    members = ",\n".join(f"      <{iri}>" for iri in classes)
    lines.append("PREFIX sd: <https://ggen.dev/ontology/strategic-doctrine#>")
    lines.append("")
    lines.append("SELECT ?subject ?class ?reason WHERE {")
    lines.append("  {")
    lines.append("    ?subject a sd:StrategicCondition ; sd:aboutClass ?class .")
    lines.append("    FILTER(?class NOT IN (")
    lines.append(members)
    lines.append("    ))")
    lines.append("    BIND(IF(")
    lines.append(ns_test + ",")
    lines.append('      "condition-over-undeclared-class-in-public-namespace",')
    lines.append('      "condition-over-non-public-class") AS ?reason)')
    lines.append("  } UNION {")
    lines.append("    ?subject a sd:StrategicCondition .")
    lines.append("    FILTER NOT EXISTS { ?subject sd:aboutClass ?any }")
    lines.append("    BIND(sd:StrategicCondition AS ?class)")
    lines.append('    BIND("condition-without-class" AS ?reason)')
    lines.append("  }")
    lines.append("}")
    lines.append("ORDER BY ?subject ?reason")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    text = render()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
        if current != text:
            print("REFUSED:GATE_PROJECTION_STALE:gates/020_applicability_public_class_only.rq", file=sys.stderr)
            return 1
        print("gate projection current: gates/020_applicability_public_class_only.rq")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(PACK_ROOT).as_posix()} sha256:{hashlib.sha256(text.encode()).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
