SELECT ?workKey ?pathScope WHERE { ?w <https://example.org/cs2#workKey> ?workKey ; <https://example.org/cs2#pathScope> ?pathScope ; <https://example.org/cs2#authority> "NONE" . } ORDER BY ?workKey ?pathScope
