SELECT ?workKey ?acceptance ?falsifier WHERE { ?w <https://example.org/cs2#workKey> ?workKey ; <https://example.org/cs2#acceptance> ?acceptance ; <https://example.org/cs2#falsifier> ?falsifier ; <https://example.org/cs2#authority> "NONE" . } ORDER BY ?workKey
