PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
SELECT ((SUM(IF(?novel = true, 1, 0)) * 1.0) / COUNT(?opportunity) AS ?noveltyRate) WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; dqv:value ?novel .
}
