PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?subject (COUNT(?relief) AS ?realizedRelief) WHERE {
  ?relief a prov:Activity ; dcterms:type "dependency-relief" ; prov:used ?opportunity .
  ?opportunity dcterms:type "actionable-opportunity" ; prov:specializationOf ?subject .
}
GROUP BY ?subject
ORDER BY DESC(?realizedRelief) ?subject
