PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?groundTruth WHERE {
  ?groundTruth a prov:Entity ; dcterms:type "grounded-actionable-opportunity" .
  FILTER NOT EXISTS { ?detected a prov:Entity ; dcterms:type "actionable-opportunity" ; prov:wasDerivedFrom ?groundTruth }
}
ORDER BY ?groundTruth
