PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?subject (COUNT(DISTINCT ?root) AS ?independentRoots) WHERE {
  ?observation a prov:Entity ; dcterms:type "seed-observation" ; prov:specializationOf ?subject ; prov:wasDerivedFrom ?root .
}
GROUP BY ?subject
ORDER BY DESC(?independentRoots) ?subject
