PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?receipt ?authority WHERE {
  ?receipt a prov:Entity ; dcterms:type "measurement-receipt" ; dcterms:rights ?authority .
  FILTER(str(?authority) != "OBSERVE|VERIFY")
}
ORDER BY ?receipt
