PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?subject (COUNT(?option) AS ?options) WHERE {
  ?option a prov:Entity ; dcterms:type "reversible-option" ; prov:specializationOf ?subject .
}
GROUP BY ?subject
ORDER BY DESC(?options) ?subject
