PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ((COUNT(DISTINCT ?opportunity) * 1.0) / COUNT(DISTINCT ?option) AS ?optionYield) WHERE {
  ?option a prov:Entity ; dcterms:type "reversible-option" .
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; prov:wasDerivedFrom ?option .
}
