PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?option WHERE {
  ?option a prov:Entity ; dcterms:type "reversible-option" .
  FILTER NOT EXISTS { ?opportunity dcterms:type "actionable-opportunity" ; prov:wasDerivedFrom ?option }
}
ORDER BY ?option
