PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
SELECT ?option ((COUNT(DISTINCT ?opportunity) * 1.0) / ?cost AS ?yieldPerCost) WHERE {
  ?option a prov:Entity ; dcterms:type "reversible-option" ; dqv:value ?cost .
  ?opportunity dcterms:type "actionable-opportunity" ; prov:wasDerivedFrom ?option .
  FILTER(?cost > 0)
}
GROUP BY ?option ?cost
ORDER BY DESC(?yieldPerCost) ?option
