PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
SELECT ?repo (COUNT(?opportunity) AS ?novelActionable) WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; dcterms:isPartOf ?repo ; dqv:value true .
}
GROUP BY ?repo
ORDER BY DESC(?novelActionable) ?repo
