PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?subject (COUNT(DISTINCT ?digest) AS ?currentDigests) WHERE {
  ?option a prov:Entity ; dcterms:type "reversible-option" ; prov:specializationOf ?subject ; dcterms:status "CURRENT" ; dcterms:identifier ?digest .
}
GROUP BY ?subject
HAVING(COUNT(DISTINCT ?digest) > 1)
ORDER BY DESC(?currentDigests) ?subject
