PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?receipt ?subject ?boundSubject WHERE {
  ?receipt a prov:Entity ; dcterms:type "measurement-receipt" ; prov:specializationOf ?boundSubject .
  ?obs a prov:Entity ; dcterms:type "seed-observation" ; prov:specializationOf ?subject ; prov:wasGeneratedBy ?receipt .
  FILTER(?subject != ?boundSubject)
}
ORDER BY ?receipt
