PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  ?capability a prov:Entity ; dcterms:type "qualified-capability" .
  FILTER NOT EXISTS {
    ?run a prov:Activity ; dcterms:type "workflow-run" ; dcterms:status "FAILURE" ; dcterms:relation "OWNING_COURT" ; prov:used ?capability .
  }
}
