PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  ?capability a prov:Entity ; dcterms:type "qualified-capability" ; dcterms:identifier ?sha .
  FILTER regex(str(?sha), "^[0-9a-f]{40}$")
}
