PREFIX ret: <https://seanchatmangpt.github.io/ontology/retrofit#>
SELECT ?i WHERE { ?i a ret:Intervention ; ret:interventionClass ret:Replacement . FILTER NOT EXISTS { ?i ret:migrationPlan ?p . ?p a ret:MigrationPlan } }
