PREFIX aex: <http://seanchatmangpt.github.io/packs/ash-extension-core#>

SELECT DISTINCT ?package_name ?module_name ?idempotency_key_source WHERE {
  ?s a aex:AshExtensionSpec ; aex:packageName ?package_name ; aex:moduleName ?module_name ;
     aex:generatesReceiptedAction "true" .
  OPTIONAL { ?s aex:receiptIdempotencyKeySource ?idempotency_key_source }
}
