PREFIX ddui: <https://chatmangpt.com/ontology/dd-ui#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?order ?kind ?id ?label
WHERE {
  ?item a ddui:VocabularyItem ;
    ddui:order ?order ;
    ddui:kind ?kind ;
    dcterms:identifier ?id ;
    skos:prefLabel ?label .
}
ORDER BY ?order ?id
