PREFIX esf: <https://ggen.dev/ontology/epistemic-sensor-factory#>
SELECT ?subject WHERE { ?sensor a esf:ManufacturedSensor ; esf:observedInRepo ?subject . } GROUP BY ?subject HAVING(COUNT(DISTINCT ?sensor)<2)
