PREFIX r73:<https://ggen.dev/measure/r73#>
SELECT ?repo ?desired ?pack ?consumer WHERE { ?repo r73:desiresStructure ?desired ; r73:exactHead ?head ; r73:standing "ALIVE" . ?desired r73:usesPack ?pack ; r73:usesGenerator ?g . ?g r73:producesArtifact ?a . ?a r73:hasConsumer ?consumer . ?consumer r73:hasQualification ?q . ?q r73:hasReceipt ?receipt . }