PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX esf: <https://ggen.dev/ontology/epistemic-sensor-factory#>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT ?r ?c WHERE { ?r a esf:QualifiedConsumerReceipt ; esf:standing "ALIVE" . ?q a dqv:QualityMeasurement ; prov:wasGeneratedBy ?r ; esf:checkConclusion ?c . FILTER(LCASE(STR(?c)) != "success") }
