defmodule GreetCli.Registry do
  @moduledoc """
  Generated by ggen (ex-noun-verb-cli-pack) from a `nvc:GeneratedCliProject`
  Turtle instance -- every entry below is `ExNounVerbCli.Registry.Generated`'s
  real `verbs:` shape (noun/verb/module/function/info/doc), so this module
  satisfies the `ExNounVerbCli.Registry` behaviour with zero hand-written
  dispatch code.
  """

  use ExNounVerbCli.Registry.Generated,
    verbs: [
      [
        noun: "greet",
        verb: "hello",
        module: GreetCli.Greet,
        function: :hello,
        info: %{schema: [name: :string], required: [:name]},
        doc: "Prints a friendly greeting for --name."
      ],

      [
        noun: "greet",
        verb: "shout",
        module: GreetCli.Greet,
        function: :shout,
        info: %{schema: [name: :string], required: [:name]},
        doc: "Prints an uppercase, shouted greeting for --name."
      ],

      [
        noun: "math",
        verb: "add",
        module: GreetCli.Math,
        function: :add,
        info: %{schema: [x: :integer, y: :integer], required: [:x, :y]},
        doc: "Adds --x and --y."
      ],

      [
        noun: "math",
        verb: "multiply",
        module: GreetCli.Math,
        function: :multiply,
        info: %{schema: [x: :integer, y: :integer], required: [:x, :y]},
        doc: "Multiplies --x and --y."
      ]
    ]
end
