//! Chicago-style CLI boundary proofs — GENERATED by chicago-tdd-tools-pack.
//!
//! Each `#[test]` dispatches through `run_boundary_spec` (the reusable,
//! real, compilable dispatch module in the sibling generated file
//! `chicago_tdd_tools_boundary_runtime.rs`, included below) which spawns a
//! real binary via `chicago_tdd_tools::cli_proof::CliHarness` and asserts
//! on observable exit codes and output. No mocks. No stubs. The binary must
//! exist on disk.

include!("chicago_tdd_tools_boundary_runtime.rs");

/// Covers: receiptctl --help exits 0 with usage text
#[test]
fn receiptctl_help_lists_verbs() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_help_lists_verbs",
        binary: "receiptctl",
        args: "--help",
        exit_code: 0,
        stdout_needle: Some("Usage"),
        stderr_needle: None,
    })
    .expect("boundary spec for receiptctl_help_lists_verbs");
}

/// Covers: receiptctl --help exits 0 with usage text
#[test]
fn receiptctl_help_lists_verbs() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_help_lists_verbs",
        binary: "receiptctl",
        args: "--help",
        exit_code: 0,
        stdout_needle: Some("Usage"),
        stderr_needle: None,
    })
    .expect("boundary spec for receiptctl_help_lists_verbs");
}

/// Covers: a known noun with an unrecognized verb exits nonzero with a clap error on stderr, distinct from an entirely-unknown top-level noun
#[test]
fn receiptctl_known_noun_unrecognized_verb_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_known_noun_unrecognized_verb_fails_closed",
        binary: "receiptctl",
        args: "algorithm frobnicate",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("unrecognized subcommand"),
    })
    .expect("boundary spec for receiptctl_known_noun_unrecognized_verb_fails_closed");
}

/// Covers: an unrecognized flag on an otherwise-valid command exits nonzero with a clap error on stderr
#[test]
fn receiptctl_unexpected_flag_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_unexpected_flag_fails_closed",
        binary: "receiptctl",
        args: "algorithm list --bogus-flag",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("unexpected argument"),
    })
    .expect("boundary spec for receiptctl_unexpected_flag_fails_closed");
}

/// Covers: an unknown subcommand exits nonzero with a clap error on stderr
#[test]
fn receiptctl_unknown_verb_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_unknown_verb_fails_closed",
        binary: "receiptctl",
        args: "frobnicate",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("error"),
    })
    .expect("boundary spec for receiptctl_unknown_verb_fails_closed");
}

/// Covers: an unknown subcommand exits nonzero with a clap error on stderr
#[test]
fn receiptctl_unknown_verb_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_unknown_verb_fails_closed",
        binary: "receiptctl",
        args: "frobnicate",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("error"),
    })
    .expect("boundary spec for receiptctl_unknown_verb_fails_closed");
}

/// Covers: receiptctl --version exits 0 and prints a version string
#[test]
fn receiptctl_version_emits_name() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_version_emits_name",
        binary: "receiptctl",
        args: "--version",
        exit_code: 0,
        stdout_needle: Some("cli "),
        stderr_needle: None,
    })
    .expect("boundary spec for receiptctl_version_emits_name");
}

