PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?pr ?sha WHERE {
  ?pr a prov:Entity ; dcterms:type "pull-request" ; dcterms:identifier ?sha ; dcterms:status "QUALIFIED" .
}
ORDER BY ?pr ?sha
