PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?pr ?head ?merge WHERE {
  ?pr a prov:Entity ; dcterms:type "pull-request" ; dcterms:identifier ?head ; dcterms:status "MERGED" ; prov:wasGeneratedBy ?merge .
}
ORDER BY ?pr ?head ?merge
