PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?opportunity ?capability WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; dcterms:identifier ?signature .
  ?capability a prov:Entity ; dcterms:type "qualified-capability" ; dcterms:subject ?signature .
}
ORDER BY ?opportunity ?capability
