PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?pr ?run ?prHead ?runHead WHERE {
  ?pr a prov:Entity ; dcterms:type "pull-request" ; dcterms:identifier ?prHead .
  ?run a prov:Activity ; dcterms:type "workflow-run" ; prov:wasAssociatedWith ?pr ; prov:used ?runHead .
  FILTER(?prHead != ?runHead)
}
ORDER BY ?pr ?run
