PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?capability ?merge ?defaultHead WHERE {
  ?capability a prov:Entity ; dcterms:type "qualified-capability" .
  ?merge a prov:Activity ; dcterms:type "merge-containment" ; prov:used ?capability ; prov:generated ?defaultHead ; dcterms:status "CONTAINED" .
}
ORDER BY ?capability ?merge
