PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?merge ?capability WHERE {
  ?merge a prov:Activity ; dcterms:type "merge-containment" ; prov:used ?capability .
  FILTER NOT EXISTS { ?capability dcterms:type "qualified-capability" }
}
ORDER BY ?merge ?capability
