PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?capability WHERE {
  ?capability a prov:Entity ; dcterms:type "qualified-capability" .
  FILTER NOT EXISTS { ?merge dcterms:type "merge-containment" ; prov:used ?capability ; dcterms:status "CONTAINED" }
}
ORDER BY ?capability
