PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?opportunity ?observedAt ?mergedAt WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; prov:generatedAtTime ?observedAt .
  ?realization dcterms:type "opportunity-realization" ; prov:used ?opportunity ; prov:generated ?capability .
  ?merge dcterms:type "merge-containment" ; prov:used ?capability ; prov:endedAtTime ?mergedAt .
}
ORDER BY ?mergedAt ?opportunity
