PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?realization ?run WHERE {
  ?realization a prov:Activity ; dcterms:type "opportunity-realization" ; prov:wasInformedBy ?run .
  ?run a prov:Activity ; dcterms:type "workflow-run" ; dcterms:status "FAILURE" .
}
ORDER BY ?realization ?run
