PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?opportunity ?capability (COUNT(?realization) AS ?duplicates) WHERE {
  ?realization a prov:Activity ; dcterms:type "opportunity-realization" ; prov:used ?opportunity ; prov:generated ?capability .
}
GROUP BY ?opportunity ?capability
HAVING(COUNT(?realization) > 1)
ORDER BY DESC(?duplicates) ?opportunity
