PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ((COUNT(DISTINCT ?realized) * 1.0) / COUNT(DISTINCT ?opportunity) AS ?closureRate) WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" .
  OPTIONAL {
    ?realized a prov:Entity ; dcterms:type "actionable-opportunity" .
    ?activity a prov:Activity ; dcterms:type "opportunity-realization" ; prov:used ?realized .
  }
}
