PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?opportunity ?capability ?merge WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; dcterms:identifier ?signature .
  ?capability a prov:Entity ; dcterms:type "qualified-capability" ; dcterms:subject ?signature .
  ?merge a prov:Activity ; dcterms:type "merge-containment" ; prov:used ?capability ; dcterms:status "CONTAINED" .
  FILTER NOT EXISTS { ?run dcterms:type "workflow-run" ; dcterms:status "FAILURE" ; prov:used ?capability ; dcterms:relation "OWNING_COURT" }
  FILTER NOT EXISTS { ?other a prov:Entity ; dcterms:type "actionable-opportunity" ; dcterms:identifier ?signature . FILTER(?other != ?opportunity) }
}
ORDER BY ?opportunity ?capability ?merge
