PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?sensor (COUNT(?run) AS ?currentRuns) WHERE { ?run a prov:Activity ; prov:wasAssociatedWith ?sensor ; dcterms:status "CURRENT" . } GROUP BY ?sensor HAVING(COUNT(?run) > 1) ORDER BY DESC(?currentRuns) ?sensor
