PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?opportunity WHERE { ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" . FILTER NOT EXISTS { ?activity prov:generated ?opportunity } } ORDER BY ?opportunity
