#!/usr/bin/env python3
"""Coverage tests binding docs/book.ttl's navigation triples to the docs/ tree.

Chicago style throughout: the collaborators are the real `docs/book.ttl` file
and the real `docs/` directory on disk, both trivially readable in-process.
Nothing here is mocked, patched, or stubbed -- there is no external or
destructive collaborator that would justify a double, and a doubled filesystem
would defeat the entire point of the check (the bug this file exists for was a
real file on disk that no triple pointed at).

Why this file exists: `docs/SUMMARY.md` is a *projection*, generated by ggen
from `mdp:NavigationEntry` triples in `docs/book.ttl` via
`packs/mdbook-pattern-language-pack/templates/SUMMARY.md.tmpl`. The Pages
workflow deletes and regenerates it (`rm -f book.toml docs/SUMMARY.md` then
`ggen sync run`), so a hand-edit to SUMMARY.md is discarded before the
published book is built. A documentation page can therefore be committed,
rendered in the repo, and still be entirely absent from the built mdBook if no
one adds its `mdp:path` triple. That happened to
`explanation/ggen-ecosystem-map.md`, and nothing in the test suite or CI
noticed. These two assertions are what makes that class of loose end
non-recurring.
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS = REPO_ROOT / "docs"
BOOK_TTL = DOCS / "book.ttl"

# Files under docs/ that are deliberately NOT mdBook chapters. Naming them as
# constants makes each exclusion a stated decision with a reason, rather than a
# silent hole that a future orphan could hide in.
#
# SUMMARY.md is the generated projection of these very triples -- it is the
# table of contents, not an entry within it.
EXCLUDED_FILES = frozenset({"SUMMARY.md"})

# superpowers/ holds skill working artifacts (plans and specs produced while
# developing this repo). They live under docs/ for convenience but are not part
# of the published book.
#
# jira/ and sjira/ are per-release ticket and failure-analysis working records
# (plans, PR review notes, milestone ledgers); context/ is the machine handoff
# and exact-head standing scratch surface. They are operational records about
# the repo's own development, not reader-facing chapters, and are deliberately
# left out of the published book.
EXCLUDED_DIRS = frozenset({"superpowers", "jira", "sjira", "context"})

MDP_PATH_RE = re.compile(r'mdp:path\s+"([^"]+)"')


def declared_nav_paths() -> set[str]:
    """Every `mdp:path` literal in the real docs/book.ttl, as a docs-relative path."""
    return set(MDP_PATH_RE.findall(BOOK_TTL.read_text(encoding="utf-8")))


def is_excluded(rel: str) -> bool:
    parts = Path(rel).parts
    return rel in EXCLUDED_FILES or (len(parts) > 1 and parts[0] in EXCLUDED_DIRS)


def markdown_files_on_disk() -> set[str]:
    """Every docs/**/*.md actually present, docs-relative, minus stated exclusions."""
    found = {
        p.relative_to(DOCS).as_posix()
        for p in DOCS.rglob("*.md")
        if p.is_file()
    }
    return {rel for rel in found if not is_excluded(rel)}


class BookNavigationCoverageTest(unittest.TestCase):
    """Both directions of the file <-> triple correspondence must hold."""

    def test_book_ttl_exists_and_declares_navigation(self) -> None:
        self.assertTrue(BOOK_TTL.is_file(), f"missing RDF source: {BOOK_TTL}")
        paths = declared_nav_paths()
        self.assertGreater(
            len(paths),
            0,
            "docs/book.ttl declares no mdp:path literals at all; the SUMMARY.md "
            "projection would render an empty book.",
        )

    def test_every_docs_markdown_file_has_a_navigation_entry(self) -> None:
        """No orphans: a page on disk that the built mdBook would never link to."""
        declared = declared_nav_paths()
        orphans = sorted(markdown_files_on_disk() - declared)
        self.assertEqual(
            orphans,
            [],
            "these docs/ pages have no mdp:NavigationEntry in docs/book.ttl, so "
            "they are absent from the generated docs/SUMMARY.md and from the "
            "published mdBook: "
            + ", ".join(orphans)
            + ". Add an entry to docs/book.ttl (never hand-edit SUMMARY.md; CI "
            "deletes and regenerates it), then re-run `ggen sync run`.",
        )

    def test_every_navigation_entry_resolves_to_an_existing_file(self) -> None:
        """No dangling links: a nav entry pointing at a file that is not there."""
        dangling = sorted(
            rel for rel in declared_nav_paths() if not (DOCS / rel).is_file()
        )
        self.assertEqual(
            dangling,
            [],
            "docs/book.ttl declares mdp:path values with no corresponding file "
            "under docs/, which would produce broken chapters in the mdBook: "
            + ", ".join(dangling),
        )

    def test_ecosystem_map_specifically_is_navigable(self) -> None:
        """Regression pin for the orphan that motivated this module."""
        self.assertIn("explanation/ggen-ecosystem-map.md", declared_nav_paths())

    def test_generated_summary_reflects_every_navigation_path(self) -> None:
        """The checked-in projection must not lag behind the RDF source.

        SUMMARY.md is regenerated in CI, so a stale checked-in copy is a silent
        divergence between what a reader browsing the repo sees and what the
        published book contains.
        """
        summary = (DOCS / "SUMMARY.md").read_text(encoding="utf-8")
        missing = sorted(
            rel for rel in declared_nav_paths() if f"({rel})" not in summary
        )
        self.assertEqual(
            missing,
            [],
            "docs/SUMMARY.md is stale relative to docs/book.ttl; regenerate it "
            "with `ggen sync run` rather than editing it. Missing: "
            + ", ".join(missing),
        )


MD_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")

HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")

# Relative markdown links are validated only inside the Diataxis quadrants:
# these are the reader-facing chapters of the published book. Other docs/
# subtrees (working records, generated artifacts) are out of scope here, the
# same way they are out of the nav-coverage surface.
LINK_SCOPED_DIRS = frozenset({"tutorials", "how-to", "reference", "explanation"})


def github_slug(text: str) -> str:
    """GitHub-style anchor slug for a markdown heading."""
    slug = text.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)  # drop punctuation, keep word chars/space/hyphen
    slug = re.sub(r"\s", "-", slug)
    return slug


def headings_of(path: Path) -> set[str]:
    """Anchor slugs of every heading in a markdown file (ATX only)."""
    slugs: set[str] = set()
    in_fence = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        match = HEADING_RE.match(line)
        if match:
            slugs.add(github_slug(match.group(2)))
    return slugs


def resolve_relative(source: Path, target: str) -> Path | None:
    """Resolve a relative link from a source file, or None if it escapes."""
    resolved = (source.parent / target).resolve()
    try:
        resolved.relative_to(REPO_ROOT.resolve())
    except ValueError:
        return None
    return resolved


class RelativeLinkCourtTest(unittest.TestCase):
    """Every relative markdown link in a Diataxis quadrant must resolve.

    Chicago style: the collaborator is the real docs/ tree on disk. A link is
    checked exactly the way a reader's renderer would check it -- resolve it
    against the linking file's directory, confirm the target file exists, and
    confirm any #fragment names a real heading (GitHub slug rules).
    """

    def test_every_relative_link_resolves_to_file_and_anchor(self) -> None:
        broken: list[str] = []
        for rel in sorted(markdown_files_on_disk()):
            parts = Path(rel).parts
            if not (len(parts) > 1 and parts[0] in LINK_SCOPED_DIRS):
                continue
            source = DOCS / rel
            for match in MD_LINK_RE.finditer(source.read_text(encoding="utf-8")):
                target = match.group(1)
                if target.startswith(("http://", "https://", "file://", "mailto:", "#")):
                    continue
                resolved = resolve_relative(source, target.split("#")[0])
                if resolved is None or not (resolved.is_file() or resolved.is_dir()):
                    broken.append(f"{rel} -> {target}")
                    continue
                fragment = target.split("#", 1)[1] if "#" in target else None
                if fragment:
                    if resolved.suffix != ".md":
                        broken.append(f"{rel} -> {target} (anchor in non-markdown)")
                    elif fragment.lower() not in {s.lower() for s in headings_of(resolved)}:
                        broken.append(f"{rel} -> {target} (missing anchor)")
        self.assertEqual(
            broken,
            [],
            "broken relative links found in docs quadrants (file or anchor "
            "unresolvable): " + "; ".join(broken),
        )


if __name__ == "__main__":
    unittest.main()
