PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX c: <urn:ggen:pack:post-agi-commerce:>
SELECT ?violation WHERE {
  FILTER NOT EXISTS {
    c:pack dcterms:conformsTo <https://github.com/seanchatmangpt/gymact/commit/1f91056fd5d4f647b219e43ad883819796bdc782> ;
      skos:note "capability-digest:c9a429501b79b7f799b7b6e8fc12d065bb1452fdd8021761d34242f257cd9032" .
  }
  BIND("exact integrated GymAct subject/digest missing" AS ?violation)
}
