# ASK true means REFUSED.
PREFIX paas: <https://chatmangpt.com/ontology/ash-r2rml-paas#>
PREFIX cv: <https://chatmangpt.com/ontology/challenger-value#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  { ?p a paas:PlatformProfile . FILTER NOT EXISTS { ?p paas:appName ?v } }
  UNION { ?p a paas:PlatformProfile . FILTER NOT EXISTS { ?p paas:moduleName ?v } }
  UNION { ?p a paas:PlatformProfile . FILTER NOT EXISTS { ?p paas:brceRequired true } }
  UNION { ?p a paas:PlatformProfile . FILTER NOT EXISTS { ?p paas:requestTimeGgen false } }
  UNION { ?p a paas:PlatformProfile . FILTER NOT EXISTS { ?p paas:innovationPolicy cv:ChallengerProjectionPolicy } }
  UNION { ?p a paas:PlatformProfile ; paas:appName ?v . FILTER(!REGEX(STR(?v), "^[a-z][a-z0-9_]*$")) }
  UNION { ?p a paas:PlatformProfile ; paas:moduleName ?v . FILTER(!REGEX(STR(?v), "^[A-Z][A-Za-z0-9]*$")) }
  UNION {
    VALUES ?required { <https://schema.org/> <http://www.w3.org/ns/prov#> <http://www.w3.org/ns/dcat#> <http://purl.org/dc/terms/> <http://www.w3.org/ns/odrl/2/> <http://qudt.org/schema/qudt/> <http://www.w3.org/2004/02/skos/core#> <http://www.w3.org/ns/shacl#> <http://www.w3.org/ns/r2rml#> <https://chatmangpt.com/ontology/challenger-value#> }
    FILTER NOT EXISTS { <https://chatmangpt.com/ontology/ash-r2rml-paas#> dcterms:conformsTo ?required }
  }
}
