PREFIX mem: <https://w3id.org/dfcm/memory#>
SELECT ?record ?field (COUNT(DISTINCT ?value) AS ?values) WHERE { ?record a mem:MemoryRecord ; mem:field ?field ; mem:value ?value ; mem:current true . } GROUP BY ?record ?field HAVING(COUNT(DISTINCT ?value) > 1)
