PREFIX mem: <https://w3id.org/dfcm/memory#>
SELECT ?receipt (COUNT(DISTINCT ?subject) AS ?subjects) WHERE { ?record mem:receipt ?receipt ; mem:exactSubject ?subject . } GROUP BY ?receipt HAVING(COUNT(DISTINCT ?subject) > 1)
