PREFIX mem: <https://w3id.org/dfcm/memory#>
SELECT ?subject (COUNT(DISTINCT ?standing) AS ?standings) WHERE { ?record mem:exactSubject ?subject ; mem:standing ?standing ; mem:current true . } GROUP BY ?subject HAVING(COUNT(DISTINCT ?standing) > 1)
