PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  ?receipt a prov:Entity ; dcterms:type "measurement-receipt" ; dcterms:rights "OBSERVE|VERIFY" ; dcterms:status "NO_DO" .
}
