PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  ?obs a prov:Entity ; dcterms:type "seed-observation" ; dcterms:identifier ?id .
  FILTER regex(str(?id), "@[0-9a-f]{40}$")
}
