PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  ?obs a prov:Entity ; dcterms:type "seed-observation" ; dcterms:status "CURRENT" ; prov:wasGeneratedBy ?receipt .
  ?receipt dcterms:type "measurement-receipt" .
}
