PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT ?class (COUNT(DISTINCT ?shape) AS ?shapeCount)
WHERE { ?shape a sh:NodeShape ; sh:targetClass ?class . }
GROUP BY ?class
HAVING(COUNT(DISTINCT ?shape) > 1)
ORDER BY STR(?class)
