PREFIX castle: <https://chatmangpt.com/ontology/castle#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?id
WHERE {
  ?source a castle:SecuritySource ;
    dcterms:identifier ?id ;
    castle:fortune5SecurityCore true .
}
ORDER BY ?id
