PREFIX dct: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?id ?action ?title ?description ?target WHERE {
  ?proposal a prov:Entity ;
            dct:identifier ?id ;
            dct:type ?category ;
            dct:title ?title ;
            dct:description ?description ;
            dct:relation ?target ;
            prov:wasGeneratedBy <urn:ggen:innovation:errc:selection> .
  ?category skos:inScheme <urn:ggen:innovation:errc> ;
            skos:prefLabel ?action ;
            skos:notation ?order .
}
ORDER BY ?order ?id
