PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
SELECT ?phase ?kind ?shape ?class ?shapeName ?path ?propertyName ?datatype ?minCount ?maxCount
WHERE {
 { ?shape a sh:NodeShape ; sh:targetClass ?class .
   FILTER(isIRI(?class)) OPTIONAL { ?shape sh:name ?shapeName . }
   BIND(10 AS ?phase) BIND("resource" AS ?kind) }
 UNION
 { ?shape a sh:NodeShape ; sh:targetClass ?class ; sh:property ?propertyShape .
   ?propertyShape sh:path ?path ; sh:datatype ?datatype .
   FILTER(isIRI(?path))
   OPTIONAL { ?shape sh:name ?shapeName . }
   OPTIONAL { ?propertyShape sh:name ?propertyName . }
   OPTIONAL { ?propertyShape sh:minCount ?minCount . }
   OPTIONAL { ?propertyShape sh:maxCount ?maxCount . }
   BIND(20 AS ?phase) BIND("attribute" AS ?kind) }
}
ORDER BY ?phase ?class ?path
