# syntax=docker/dockerfile:1
FROM scratch
ARG TARGETARCH
COPY factory/bin/${TARGETARCH}/ggen /factory/bin/ggen
COPY factory/marketplace /factory/marketplace
COPY factory/factory-manifest.json /factory/factory-manifest.json
LABEL io.ggen.package.kind="ggen-factory"
LABEL io.ggen.package.layout="/factory"
CMD ["/factory/bin/ggen"]
