defmodule Xaas.Governance.LegalHoldRelease do
  @moduledoc """
  Generated by ggen from pcc:ApprovalLegalHoldRelease (chatman-ecosystem
  ontology/platform-console-capabilities.ttl). This module is a
  PROJECTION of the admitted capability graph, not ontology truth --
  regenerate from the source ontology, do not hand-edit the generated
  block below.

  Source capability facts:
    title:              legal-hold.release
    capabilityClass:     ce:Do
    executionOwner:      platform-console
    requiredAuthority:    approval-workflow.requireApproval(legal-hold.release)
    brokerRequired:       true
    receiptRequired:      true
    reversible:           false
  """
  use Ash.Resource,
    domain: Xaas.Governance,
    data_layer: Ash.DataLayer.Ets

  attributes do
    uuid_primary_key :id
    attribute :requested_by, :string, allow_nil?: false
    attribute :approved_by, :string, allow_nil?: true
    attribute :status, :atom, constraints: [one_of: [:pending, :approved, :refused]], default: :pending
  end

  actions do
    defaults [:read]

    # release: gated by requiredAuthority = "approval-workflow.requireApproval(legal-hold.release)"
    # brokerRequired=true, receiptRequired=true,
    # reversible=false -- reversible=false is a comment marker only in
    # this proof; no destructive default action is generated from it (open
    # question, not resolved by this template).
    update :release do
      accept []
      argument :approved_by, :string, allow_nil?: false

      # Change -> Intent, never Change -> external system (settled law).
      # This change constructs an intent for the BRCE broker; it never
      # calls platform-console's legal-hold.ts or any external system
      # directly -- Ash.Policy below answers "may actor call this
      # action," which is NOT equivalent to BRCE execution authority.
      change set_attribute(:status, :approved)
      change set_attribute(:approved_by, arg(:approved_by))
    end
  end

  policies do
    policy action(:release) do
      # requiredAuthority = "approval-workflow.requireApproval(legal-hold.release)" -- rendered here as
      # an Ash.Policy authorization gate on the INTERNAL action call.
      # This is distinct from, and does not substitute for, the BRCE
      # broker/receipt check the real capability's brokerRequired=true /
      # receiptRequired=true facts still require before actuation.
      authorize_if actor_attribute_equals(:role, :owner)
    end
  end
end
