PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?qualified ?merge ?default WHERE {
  ?merge a prov:Activity ; dcterms:type "merge-containment" ; prov:used ?qualified ; prov:generated ?default ; dcterms:status "CONTAINED" .
} ORDER BY ?qualified ?merge
