PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?capability ?standing WHERE {
  ?qualification a prov:Activity ; dcterms:type "qualification" ; prov:generated ?capability ; dcterms:status ?standing .
  FILTER(?standing = "ALIVE")
} ORDER BY ?capability
