PREFIX qcb: <https://seanchatmangpt.github.io/packs/qri-consumer-binding-pack#>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT ?pin WHERE { ?pin a qcb:ArtifactPin . FILTER NOT EXISTS { ?pin prov:wasDerivedFrom ?producer . FILTER(REGEX(STR(?producer), "^https://github[.]com/[^/]+/[^/]+/commit/[0-9a-f]{40}$")) } }
