# GENERATED by ggen_igniter (sibling of beam4pm_actuation.ex.eex). Do not edit.
defmodule BeamPM.ReceiptChain do
  @moduledoc """
  Hash-chained-receipt extension (stream EX2) for `beam4pm-brce/v1`
  consequence receipts, adapted from ex4pm's real
  `Ex4pm.Evidence.Replay.Chain` (`apps/ex4pm_evidence/lib/ex4pm/evidence/
  replay_chain.ex`).

  ## What ex4pm actually does, and what is kept vs. diverges here

  ex4pm's `Ex4pm.Evidence.Receipt.outcome/4` embeds a `parent_hash` equal to
  its pending sibling's own `hash` (itself `Hash.digest/1` of that receipt's
  payload); `Ex4pm.Evidence.Replay.Chain.verify/2` then (1) recomputes the
  child's own hash from its payload, (2) looks the parent up BY HASH in an
  `Ex4pm.Evidence.Store` (ETS, or the restart-durable `Ex4pm.Evidence.
  DetsStore` swapped in via the same `store` argument), (3) recomputes the
  PARENT's own hash too, and (4) cross-checks subject_hash/operation/
  authority_hash correspondence between them. Critically, step (3) is what
  catches a stored-but-tampered parent even when the child referencing it
  is untouched (`replay_chain_test.exs`, "chain verification catches a
  stored pending parent tampered after the fact").

  beam4pm's receipts are already independent JSON FILES on disk, not
  ETS/DETS-keyed terms -- unlike ex4pm's default in-memory ETS `Store`,
  every beam4pm receipt is ALREADY restart-durable evidence the moment
  `write_receipt!/2` returns. Introducing a DETS table on top would mean
  keeping two parallel representations of the same evidence (the existing
  human/tool-readable JSON files, plus a binary DETS term store) in sync for
  no durability gain beam4pm doesn't already have -- ex4pm's own moduledoc
  even frames `DetsStore` as a "candidate" backing swapped in behind the
  same `Store` interface, not the sole mechanism. So this module keeps
  beam4pm's flat-file design and adds ONLY the missing capability: a
  cryptographic link from receipt N to receipt N-1 and a real, independent
  recomputation that walks a receipts directory and proves the link is
  unbroken.

  The one place this necessarily diverges from ex4pm's byte-for-byte
  approach: ex4pm hashes an IN-MEMORY payload map (a struct's own fields,
  computed once, before serialization) with a domain-specific
  `Ex4pm.Core.Hash.digest/1`. A file-based ledger has no such in-memory
  payload to re-hash independently of serialization -- the file on disk IS
  the payload. So `hash_file!/1` hashes the EXACT RAW BYTES of the receipt
  file as written (`sha256`, hex-encoded), never a re-decoded-then-
  re-encoded map. This is actually a STRONGER recomputation than
  decode-then-rehash would be: it has zero dependency on JSON key-order or
  number-formatting stability across a decode/encode round trip, and it
  catches literally any byte-level tampering of the file, not just
  tampering that survives a JSON round trip.

  ## What "immediately prior" means here (this module's own design choice)

  ex4pm's parent/child link is a 1:1 relationship between exactly two
  receipts (a pending and its own outcome) -- there is no ambient
  N-receipt sequence to scope by. beam4pm has no such natural 1:1 pairing
  for its BRCE receipts (`beam4pm-brce/v1` receipts are already a complete,
  self-contained pending+outcome envelope in one file). The natural
  N-receipt SEQUENCE that already exists in beam4pm is
  `BeamPM.ProcessGovernor`'s per-process ordinal sequence (t1, t2, ...) --
  so chaining is scoped by an explicit `chain_id` (a plain string), and
  `BeamPM.ProcessGovernor.apply_transition/3` defaults `chain_id` to its
  `process_id` automatically. A bare `BeamPM.Actuation.run/2` call (no
  governing process) has no ambient sequence to join by default, so it
  gets NO chain fields at all unless the caller passes `chain_id:` -- this
  keeps every existing bare-actuation receipt's shape byte-for-byte
  unchanged (fully additive, opt-in, zero regression to
  `BeamPM.ActuationTest`'s existing assertions).

  ## The four fields added to an opted-in `beam4pm-brce/v1` receipt

    * `"chain_id"` - the caller- or `ProcessGovernor`-supplied chain scope.
    * `"chain_seq"` - 1-based ordinal within that chain (1 = genesis).
    * `"prev_receipt_path"` - path to the immediately-prior receipt in this
      chain, or `nil` for the genesis receipt. A convenience pointer only
      (mirrors `BeamPM.ProcessGovernor`'s own embed-by-reference
      convention for its `"actuation"` field) -- `verify/2` below never
      trusts it blindly; it independently reconstructs chain order from
      each receipt's own recorded `"chain_seq"`.
    * `"prev_receipt_hash"` - `sha256` hex digest of the immediately-prior
      receipt file's raw bytes AT THE MOMENT this receipt was written, or
      `nil` for the genesis receipt.

  ## Concurrency (disclosed limitation, honestly stated)

  `link_fields/2` determines the next link by scanning `receipts_dir` for
  the highest existing `"chain_seq"` for `chain_id` -- there is no lock.
  Two concurrent writers targeting the SAME `chain_id` could race and pick
  the same `chain_seq`/parent. This module makes the same assumption
  `BeamPM.ProcessGovernor.apply_transition/3` already makes for its own
  process receipts (one process advanced sequentially by one caller) --
  it does not add cross-process/cross-node locking. A genuinely concurrent
  writer story is out of scope for this additive extension.
  """

  @actuation_receipt_schema "beam4pm-brce/v1"

  @typedoc "The four chain fields to merge into a beam4pm-brce/v1 receipt map before writing."
  @type link :: %{
          chain_id: String.t(),
          chain_seq: pos_integer(),
          prev_receipt_path: String.t() | nil,
          prev_receipt_hash: String.t() | nil
        }

  @doc """
  Computes the chain-linkage fields for the NEXT `beam4pm-brce/v1` receipt
  about to be written to `receipts_dir` for `chain_id`. Scans `receipts_dir`
  (top-level `*.json` files only -- `BeamPM.ProcessGovernor`'s own
  `process/` subdirectory holds a different `receipt_schema`,
  `beam4pm-process-governor/v1`, and is never a chain-link candidate) for
  existing receipts already carrying that exact `"chain_id"`, and links to
  whichever one carries the highest `"chain_seq"`. No existing receipt for
  this `chain_id` is genesis: `chain_seq: 1`, both prev-fields `nil`.
  """
  @spec link_fields(String.t(), String.t()) :: link()
  def link_fields(receipts_dir, chain_id) when is_binary(receipts_dir) and is_binary(chain_id) do
    case tip(receipts_dir, chain_id) do
      nil ->
        %{chain_id: chain_id, chain_seq: 1, prev_receipt_path: nil, prev_receipt_hash: nil}

      %{path: path, chain_seq: seq} ->
        %{
          chain_id: chain_id,
          chain_seq: seq + 1,
          prev_receipt_path: path,
          prev_receipt_hash: hash_file!(path)
        }
    end
  end

  @doc "sha256 hex digest of the exact bytes currently on disk at `path`."
  @spec hash_file!(String.t()) :: String.t()
  def hash_file!(path) when is_binary(path) do
    path
    |> File.read!()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  @doc """
  Real, independent replay verification: walks every `beam4pm-brce/v1`
  receipt in `receipts_dir` belonging to `chain_id`, orders them by their
  own recorded `"chain_seq"`, and for each non-genesis link RECOMPUTES
  `sha256` of the immediately-prior receipt's file bytes AS THEY EXIST ON
  DISK RIGHT NOW (never trusts any recorded hash, never trusts
  `"prev_receipt_path"` for anything but a starting guess) and confirms the
  recomputed digest equals the current receipt's own recorded
  `"prev_receipt_hash"`. This catches tampering of ANY receipt in the
  chain -- not only the newest one -- because every receipt downstream of a
  tampered file has its own independently-recorded `prev_receipt_hash` to
  compare against a hash computed fresh from disk on this call, exactly
  mirroring ex4pm's `Ex4pm.Evidence.Replay.Chain` "tampered stored parent,
  untouched child" guarantee (`replay_chain_test.exs`) -- adapted here to a
  file-based ledger instead of an ETS/DETS-keyed store.

  Returns `{:ok, %{chain_id: chain_id, length: n, receipt_paths: paths}}`
  (oldest-first `paths`) for a fully unbroken chain, including the vacuous
  `length: 0` case (no receipts recorded for this `chain_id` yet -- not a
  break). Returns `{:error, {:chain_broken, seq, reason}}` at the first
  link that fails, where `reason` is one of:

    * `:hash_mismatch` - the prior receipt's current on-disk bytes no
      longer hash to what this receipt recorded.
    * `:missing_receipt_file` - the prior receipt this chain_seq depends on
      is not on disk at all.
    * `:genesis_must_have_no_parent` - the seq-1 receipt records a non-nil
      `prev_receipt_hash`.
    * `:duplicate_or_missing_seq` - the recorded `"chain_seq"` values for
      this `chain_id` are not exactly `1..n` with no gaps or repeats (this
      also fires when a receipt's JSON body no longer decodes at all, since
      it then silently drops out of the scan and leaves a gap).
  """
  @spec verify(String.t(), String.t()) ::
          {:ok, %{chain_id: String.t(), length: non_neg_integer(), receipt_paths: [String.t()]}}
          | {:error, {:chain_broken, non_neg_integer(), atom()}}
  def verify(receipts_dir, chain_id) when is_binary(receipts_dir) and is_binary(chain_id) do
    receipts = receipts_dir |> chain_receipts(chain_id) |> Enum.sort_by(& &1.chain_seq)

    with :ok <- assert_contiguous_seq(receipts) do
      receipts
      |> Enum.reduce_while({:ok, []}, fn receipt, {:ok, acc} ->
        case verify_link(receipt, receipts) do
          :ok -> {:cont, {:ok, [receipt.path | acc]}}
          {:error, reason} -> {:halt, {:error, {:chain_broken, receipt.chain_seq, reason}}}
        end
      end)
      |> case do
        {:ok, paths} ->
          {:ok, %{chain_id: chain_id, length: length(paths), receipt_paths: Enum.reverse(paths)}}

        {:error, _} = err ->
          err
      end
    end
  end

  # -- internal ---------------------------------------------------------

  defp tip(receipts_dir, chain_id) do
    receipts_dir
    |> chain_receipts(chain_id)
    |> Enum.max_by(& &1.chain_seq, fn -> nil end)
  end

  defp chain_receipts(receipts_dir, chain_id) do
    case File.ls(receipts_dir) do
      {:ok, entries} ->
        entries
        |> Enum.map(&Path.join(receipts_dir, &1))
        |> Enum.filter(&(String.ends_with?(&1, ".json") and File.regular?(&1)))
        |> Enum.flat_map(&decode_chain_receipt(&1, chain_id))

      {:error, _} ->
        []
    end
  end

  defp decode_chain_receipt(path, chain_id) do
    with {:ok, raw} <- File.read(path),
         {:ok, decoded} <- JSON.decode(raw),
         true <- decoded["receipt_schema"] == @actuation_receipt_schema,
         true <- decoded["chain_id"] == chain_id,
         seq when is_integer(seq) <- decoded["chain_seq"] do
      [
        %{
          path: path,
          chain_seq: seq,
          prev_receipt_hash: decoded["prev_receipt_hash"],
          prev_receipt_path: decoded["prev_receipt_path"]
        }
      ]
    else
      _ -> []
    end
  end

  defp assert_contiguous_seq([]), do: :ok

  defp assert_contiguous_seq(receipts) do
    seqs = Enum.map(receipts, & &1.chain_seq)

    if seqs == Enum.to_list(1..length(seqs)//1) do
      :ok
    else
      {:error, {:chain_broken, List.first(seqs) || 0, :duplicate_or_missing_seq}}
    end
  end

  defp verify_link(%{chain_seq: 1} = receipt, _all) do
    if receipt.prev_receipt_hash == nil do
      :ok
    else
      {:error, :genesis_must_have_no_parent}
    end
  end

  defp verify_link(%{chain_seq: seq} = receipt, all) do
    case Enum.find(all, &(&1.chain_seq == seq - 1)) do
      nil ->
        {:error, :duplicate_or_missing_seq}

      %{path: prev_path} ->
        if File.exists?(prev_path) do
          if hash_file!(prev_path) == receipt.prev_receipt_hash do
            :ok
          else
            {:error, :hash_mismatch}
          end
        else
          {:error, :missing_receipt_file}
        end
    end
  end
end
