#!/usr/bin/env bash
# GENERATED by ggen sync from ontology.ttl. Real, complete generation -- per
# ash-project/ash@main:lib/mix/tasks/gen/ash.gen.enum.ex (read directly,
# 120 lines): this task writes a full, real Ash.Type.Enum module with real
# values from the CLI arg list (`use Ash.Type.Enum, values: [...]`,
# ash.gen.enum.ex:66-70). Unlike ash.gen.change/validation/preparation, this
# is NOT a stub-generating task -- there is no follow-on hand-authoring gap
# for this one.
#
# Values are the real 4 ce:CapabilityClass individuals declared in
# ontology/capabilities.ttl (ce:Observe, ce:Select, ce:Construct, ce:Do --
# confirmed via `grep -n "a ce:CapabilityClass" capabilities.ttl`; all 44
# platform-console-capabilities.ttl individuals are currently ce:Do, but the
# TBox defines all 4). ce:standing is NOT emitted as an enum here -- checked
# directly against capabilities.ttl:61 (`ce:standing a owl:DatatypeProperty ;
# rdfs:range xsd:string`), it has no declared controlled vocabulary, only
# "active" is observed on any of the 44 individuals. Generating an enum with
# invented values ("deprecated","retired") that aren't in the real ontology
# would be exactly the fabrication this pass exists to stop doing.
set -euo pipefail

echo "=== XaaS Ash enums (ggen-generated): $(date) ==="

mix ash.gen.enum Xaas.Types.CapabilityClass observe,select,construct,do --short-name capability_class --yes

mix compile
echo "=== Done: $(date) ==="
