#!/usr/bin/env bash
# GENERATED by ggen sync from ontology.ttl. Real, project-wide, non-per-row
# generation -- per ash-project/ash@main:lib/mix/tasks/ash.codegen.ex (83
# lines) and lib/mix/tasks/ash.migrate.ex (32 lines), both read directly.
#
# Must run AFTER Part 3 (xaas-ash-build-extend-GENERATED.sh) extends every
# resource from `ets` to `postgres,json_api,graphql` -- ash.codegen only has
# something real to generate once AshPostgres.DataLayer is actually the
# resource's data layer. Running this before the extend pass would find
# nothing to codegen (ETS has no migrations).
#
# `mix ash.codegen` is a data-layer-agnostic dispatcher (confirmed from
# source: it iterates Ash.Mix.Tasks.Helpers.extensions!() and calls
# extension.codegen/1 on any extension exporting codegen/1 -- for
# AshPostgres that means real migration file + resource snapshot
# generation, per ash_postgres's own migrations-and-tasks docs). It takes a
# required positional `name` argument (not a --yes flag -- confirmed absent
# from its schema in source) used to name the generated migration file.
#
# `mix ash.migrate` is the same dispatch pattern for actually running the
# generated migrations against the real database (no flags in its source
# beyond passthrough argv to extensions).
#
# PREREQUISITE (real, not assumed): a real Postgres instance reachable via
# this project's config/dev.exs DATABASE_URL. If none is running, this step
# will fail with a real connection error -- that is a correct, honest
# failure, not something ggen should paper over with a fake success.
set -euo pipefail

echo "=== XaaS Ash codegen + migrate (ggen-generated): $(date) ==="

mix ash.codegen xaas_resources
mix ash.migrate

echo "=== Done: $(date) ==="
