//! GENERATED by ggen from gym-upper-ontology-pack. Do not edit.
//!
//! Crosswalk over the consequence-class encodings the gym packs each minted
//! separately. gu:DO is an INTENT class: nothing here grants runtime authority;
//! consequential DO remains behind external GymAct/BRCE admission.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConsequenceClass { pub notation: &'static str, pub label: &'static str }

pub const CONSEQUENCE_CLASSES: &[ConsequenceClass] = &[
ConsequenceClass { notation: "DO", label: "do" },
ConsequenceClass { notation: "READ", label: "read" },
];

/// Legacy IRIs that other packs already reference; each resolves to a notation here.
pub const LEGACY_IRI_ALIASES: &[(&str, &str)] = &[
("urn:gymact:consequence:do", "DO"),
("urn:gymact:consequence:read", "READ"),
];

/// (capability id, consequence notation, source encoding) resolved across every
/// spelling found in the real gym ontologies.
pub const RESOLVED_CAPABILITIES: &[(&str, &str, &str)] = &[
("allocate_capacity", "DO", "dct:relation-literal"),
("assess_profile", "DO", "dct:relation-literal"),
("assess_resilience_baseline", "DO", "dct:relation-literal"),
("get_benchmark_status", "DO", "dcp:consequence-literal"),
("inject_resilience_stressor", "DO", "dct:relation-literal"),
("inspect-capability-catalog", "READ", "dct:type-iri"),
("inspect-environment", "READ", "dct:type-iri"),
("jaeger_get_dependency_graph", "DO", "dcp:consequence-literal"),
("jaeger_get_operations", "DO", "dcp:consequence-literal"),
("jaeger_get_services", "DO", "dcp:consequence-literal"),
("jaeger_get_traces", "DO", "dcp:consequence-literal"),
("link_dependency", "DO", "dct:relation-literal"),
("loki_get_label_values", "DO", "dcp:consequence-literal"),
("loki_get_labels", "DO", "dcp:consequence-literal"),
("loki_get_logs", "DO", "dcp:consequence-literal"),
("observe_cluster_state", "DO", "dcp:consequence-literal"),
("prometheus_get_alerts", "DO", "dcp:consequence-literal"),
("prometheus_get_metrics", "DO", "dcp:consequence-literal"),
("propose_requirement", "DO", "dct:relation-literal"),
("record_consensus", "DO", "dct:relation-literal"),
("record_exercise_observation", "DO", "dct:relation-literal"),
("record_tevv_evidence", "DO", "dct:relation-literal"),
("register_capability_target", "DO", "dct:relation-literal"),
("register_data_product", "DO", "dct:relation-literal"),
("register_innovation_path", "DO", "dct:relation-literal"),
("register_investment", "DO", "dct:relation-literal"),
("register_lesson", "DO", "dct:relation-literal"),
("register_pace_plan", "DO", "dct:relation-literal"),
("register_supply_chain_risk", "DO", "dct:relation-literal"),
("reset-simulation", "DO", "dct:type-iri"),
("review_readiness", "DO", "dct:relation-literal"),
("run_kubectl", "DO", "dcp:consequence-literal"),
("simulate-capability", "DO", "dct:type-iri"),
("submit_diagnosis", "DO", "dcp:consequence-literal"),
("submit_mitigation", "DO", "dcp:consequence-literal"),
];

pub fn resolve_legacy_iri(iri: &str) -> Option<&'static str> {
    LEGACY_IRI_ALIASES.iter().find(|(a, _)| *a == iri).map(|(_, n)| *n)
}

pub fn consequence_of(id: &str) -> Option<&'static str> {
    RESOLVED_CAPABILITIES.iter().find(|(c, _, _)| *c == id).map(|(_, n, _)| *n)
}
