PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?qualified WHERE {
  ?qualified a prov:Entity ; dcterms:type "qualified-subject" .
  FILTER NOT EXISTS { ?merge dcterms:type "merge-containment" ; prov:used ?qualified ; dcterms:status "CONTAINED" }
}
ORDER BY ?qualified
