PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?opportunity ?observedAt ?realizedAt WHERE {
  ?opportunity a prov:Entity ; dcterms:type "actionable-opportunity" ; prov:generatedAtTime ?observedAt .
  ?activity a prov:Activity ; dcterms:type "opportunity-realization" ; prov:used ?opportunity ; prov:endedAtTime ?realizedAt .
}
ORDER BY ?realizedAt ?opportunity
