PREFIX rmc: <https://w3id.org/dfcm/revalidation-manufacturing#>
SELECT (COUNT(?candidate) AS ?count) WHERE { ?candidate a rmc:RevalidationCandidate ; rmc:requiresRevalidation false ; rmc:consequentialDo false . }
