#!/usr/bin/env python3
"""Generate docs/reference/PACK-INDEX.md: one row per pack under packs/.

Regenerate with: python3 scripts/gen_pack_index.py
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import marketplace_lifecycle  # noqa: E402

OUT = ROOT / "docs" / "reference" / "PACK-INDEX.md"

HEADER = (
    "# Pack Index\n"
    "\n"
    "<!-- GENERATED by scripts/gen_pack_index.py from packs/ + lifecycle.toml. -->\n"
    "<!-- Edit pack.toml / lifecycle.toml, not this file. Regenerate: `python3 scripts/gen_pack_index.py`. -->\n"
    "\n"
    "One row per pack directory under `packs/` ({n} packs: {n_active} active, {n_deprecated} deprecated).\n"
    "Profiles follow `scripts/marketplace.py`'s `Pack.profile`: `project` (ggen.toml present), "
    "`projection` (templates), `semantic` (otherwise). Lifecycle state is the canonical "
    "`lifecycle.toml` registry; packs absent from the registry default to `active`.\n"
    "\n"
    "| Pack | Profile | Lifecycle | Purpose |\n"
    "|---|---|---|---|\n"
)

DEPRECATED_SECTION = "\n## Deprecated packs\n\n"

DEPRECATED_ROW = (
    "- [{name}]({link}) — deprecated{since}: capabilities consolidated into "
    "[{succ}]({succ_link}). See the pack's [DEPRECATED.md]({dep_link})."
)


def one_line(text: str) -> str:
    """Collapse to one table-safe line: no newlines, no raw pipes."""
    return " ".join(text.split()).replace("|", "\\|")


def load_pack(path: Path) -> dict:
    with (path / "pack.toml").open("rb") as handle:
        return tomllib.load(handle)["pack"]


def profile_of(path: Path) -> str:
    if (path / "ggen.toml").is_file():
        return "project"
    templates = path / "templates"
    if templates.is_dir() and any(templates.iterdir()):
        return "projection"
    return "semantic"


def main() -> int:
    registry, _ = marketplace_lifecycle.load(ROOT)
    pack_dirs = sorted(
        (p for p in (ROOT / "packs").iterdir() if (p / "pack.toml").is_file()),
        key=lambda p: p.name,
    )
    rows = []
    deprecated_rows = []
    for path in pack_dirs:
        table = load_pack(path)
        name = table["name"]
        description = table.get("description", "")
        status = "active"
        if name in registry:
            status = registry[name].get("state", "active")
        rows.append(
            f"| [{name}](../../packs/{path.name}/) | {profile_of(path)} | {status} | {one_line(description)} |"
        )
        if status == "deprecated":
            deprecated_rows.append((name, path.name))
    header = HEADER.format(
        n=len(rows),
        n_active=len(rows) - len(deprecated_rows),
        n_deprecated=len(deprecated_rows),
    )
    lines = [header.rstrip("\n")]
    lines.extend(rows)
    lines.append(DEPRECATED_SECTION.rstrip("\n"))
    registry_entries = marketplace_lifecycle.load(ROOT)[0]
    for name, dirname in deprecated_rows:
        entry = registry_entries[name]
        successors = entry.get("successors", [])
        successor = successors[0] if successors else "rust-wasi-wasmex-pack"
        since = f" (since {entry.get('since')})" if entry.get("since") else ""
        dep_md = (ROOT / "packs" / dirname / "DEPRECATED.md").is_file()
        dep_link = f"../../packs/{dirname}/DEPRECATED.md" if dep_md else None
        tail = (
            f" See the pack's [DEPRECATED.md]({dep_link})." if dep_link else ""
        )
        lines.append(
            f"- [{name}](../../packs/{dirname}/) — deprecated{since}: capabilities "
            f"consolidated into [{successor}](../../packs/{successor}/).{tail}"
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} packs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
