#!/usr/bin/env python3
"""Deterministic generator of the marketplace standing table.

Writes (or checks) the region between <!-- GENERATED:standing --> and
<!-- /GENERATED:standing --> in docs/context/standing.md and
docs/reference/standing.md. Every count is derived from the pack tree; nothing
is hand-written inside the markers.

The recorded head SHA is provenance, not content identity: a commit cannot
contain its own hash, so --check compares the SHA line only when --sha is given.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import marketplace  # noqa: E402

ROOT = marketplace.ROOT
TARGETS = (ROOT / "docs/context/standing.md", ROOT / "docs/reference/standing.md")
BEGIN = "<!-- GENERATED:standing -->"
END = "<!-- /GENERATED:standing -->"
SHA_LINE = re.compile(r"^- Head SHA: .*$", re.M)


def run(*cmd: str) -> str:
    result = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise SystemExit(f"REFUSED:STANDING_COMMAND_FAILED {' '.join(cmd)}: {result.stderr.strip()}")
    return result.stdout.strip()


def head_sha() -> str:
    return run("git", "rev-parse", "HEAD")


def catalog_fingerprint() -> str:
    return run(sys.executable, str(ROOT / "scripts/marketplace.py"), "fingerprint").split()[0]


def tier_signals(pack: marketplace.Pack) -> str:
    signals = []
    if pack.name in marketplace.DEPRECATED_PACKS:
        signals.append("deprecated")
    if pack.native_gates:
        signals.append("native-gates")
    if pack.verifier_gates:
        signals.append("verifier-gates")
    if pack.templates:
        signals.append("templates")
    pack_class = marketplace.PACK_CLASSES.get(pack.name)
    if pack_class:
        signals.append(pack_class)
    return ", ".join(signals) if signals else "ontology-only"


def render(sha: str) -> str:
    packs, issues = marketplace.inspect_marketplace()
    if issues:
        raise SystemExit("REFUSED:MARKETPLACE_INVALID " + "; ".join(issues[:3]))
    packs = sorted(packs, key=lambda p: p.name)
    lines = [
        BEGIN,
        "<!-- Generated by scripts/standing.py; do not edit by hand. -->",
        "",
        "### Repository facts",
        "",
        f"- Marketplace version: `{marketplace.marketplace_version()}`",
        f"- Pack count: {len(packs)}",
        f"- Catalog fingerprint: `{catalog_fingerprint()}`",
        f"- Head SHA: `{sha}`",
        "",
        "### Pack standing table",
        "",
        "Tier signals are structural observations (gates, templates, class), not ALIVE claims.",
        "",
        "| Pack | Version | Profile | Tier signals |",
        "|---|---|---|---|",
    ]
    for pack in packs:
        lines.append(f"| {pack.name} | {pack.version} | {pack.profile} | {tier_signals(pack)} |")
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str | None:
    """Replace the marked region; None when markers are absent."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        return None
    return text[:start] + block + text[end + len(END):]


def normalize(text: str, ignore_sha: bool) -> str:
    return SHA_LINE.sub("- Head SHA: *", text) if ignore_sha else text


def label(target: Path) -> str:
    try:
        return str(target.resolve().relative_to(ROOT))
    except ValueError:
        return str(target)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit nonzero if generated regions are stale")
    parser.add_argument("--sha", help="head SHA to record (default: git rev-parse HEAD)")
    parser.add_argument("--target", action="append", type=Path,
                        help="markdown file to update/check (repeatable; default: the two standing docs)")
    args = parser.parse_args()
    block = render(args.sha or head_sha())
    stale = []
    for target in (args.target or TARGETS):
        text = target.read_text(encoding="utf-8")
        updated = splice(text, block)
        if updated is None:
            stale.append(f"{label(target)}: markers missing")
            continue
        if args.check:
            if normalize(updated, args.sha is None) != normalize(text, args.sha is None):
                stale.append(f"{label(target)}: stale")
        elif updated != text:
            target.write_text(updated, encoding="utf-8")
            print(f"updated {label(target)}")
    if stale:
        for item in stale:
            print(f"REFUSED:STANDING_STALE {item}", file=sys.stderr)
        return 1
    if args.check:
        print("standing: fresh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
