# MESSAGE: VALUE_INNOVATION_RECEIPT_DIGEST_ALGORITHM_REQUIRED
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
SELECT ?receipt WHERE { ?receipt a vi:DecisionReceipt . FILTER NOT EXISTS { ?receipt vi:digestAlgorithm ?algorithm } }