# MESSAGE: VALUE_INNOVATION_CURVE_POINT_LEVEL_REQUIRED
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
SELECT ?point WHERE { ?point a vi:CurvePoint . FILTER NOT EXISTS { ?point vi:offeringLevel ?level } }