# MESSAGE: VALUE_INNOVATION_CURVE_POINT_LEVEL_NUMERIC
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
SELECT ?point ?level WHERE { ?point a vi:CurvePoint ; vi:offeringLevel ?level . FILTER (!isNumeric(?level)) }