# MESSAGE: VALUE_INNOVATION_CURVE_FACTOR_DUPLICATE
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
SELECT ?curve ?factor WHERE { ?a a vi:CurvePoint ; vi:curve ?curve ; vi:factor ?factor . ?b a vi:CurvePoint ; vi:curve ?curve ; vi:factor ?factor . FILTER (?a != ?b) }