# MESSAGE: VALUE_INNOVATION_PARETO_DELTA_DIMENSION_REQUIRED
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
SELECT ?delta WHERE { ?delta a vi:ParetoDelta . FILTER NOT EXISTS { ?delta vi:dimension ?dimension } }