# MESSAGE: VALUE_INNOVATION_PARETO_PROTECTED_FLAG_INVALID
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
SELECT ?delta ?protected WHERE { ?delta a vi:ParetoDelta ; vi:protected ?protected . FILTER (?protected != true && ?protected != false) }