# MESSAGE: VALUE_INNOVATION_DESIGN_SPACE_UNTYPED
PREFIX vi: <http://seanchatmangpt.github.io/packs/value-innovation-errc#>
PREFIX cmd: <https://chatmangpt.com/ontology/cmd#>
SELECT ?grid ?space WHERE { ?grid a vi:StrategyGrid ; vi:designSpace ?space . FILTER NOT EXISTS { ?space a cmd:DesignSpace } }