PREFIX pf: <https://ggen.io/marketplace/planning-federation#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?domain ?initial ?goal ?action ?pre ?effect ?cost ?duration ?probability ?authority WHERE {
  pf:AdmittedDemo skos:prefLabel ?domain ;
    pf:initialPredicate ?initial ;
    pf:goalPredicate ?goal .
  ?a a pf:PlannableAction ;
    skos:prefLabel ?action ;
    pf:precondition ?pre ;
    pf:effect ?effect ;
    pf:cost ?cost ;
    pf:duration ?duration ;
    pf:probability ?probability ;
    pf:authorityRef ?authority .
}
ORDER BY ?action
