//! Zero-config clap-noun-verb starter: rename me, then add nouns and commands.
//!
//! GENERATED by ggen from an admitted RDF graph. The crate contains no
//! consumer-authored Rust behavior or routing seams.

#![forbid(unsafe_code)]
#![deny(rust_2018_idioms, unused_must_use)]

pub mod generated_behavior;
pub mod generated_boundaries;
pub mod generated_cli;

/// Discover and execute the generated noun-verb registry.
pub fn run() -> clap_noun_verb::Result<()> {
    clap_noun_verb::run()
}
