#!/usr/bin/env bash
# COMMITTED (non-generated) bootstrap copy of the evidence emitter.
#
# Why this file exists -- the chicken-and-egg this pack creates by design:
# ggen-verify-pack's gates run on EVERY sync (pack gates/*.rq are evaluated
# unconditionally in crates/ggen-engine/src/sync.rs Stage 2b), including the
# very first sync that would generate the consumer's scripts/verify-evidence.sh
# emitter from templates/verify_evidence_sh.tmpl. A fresh consumer therefore
# has no emitter and no evidence, and sync refuses (FM-PACK-013, gate 010).
#
# Resolution (two-phase bootstrap, documented in ../README.md):
#   Phase 1: from the consumer root, run THIS committed copy once:
#              bash packs/ggen-verify-pack/bootstrap/verify-evidence-bootstrap.sh
#            It scaffolds the evidence/ mini-pack and records real evidence.
#   Phase 2: `ggen sync run` now passes the gates and generates
#            scripts/verify-evidence.sh; use THAT from then on (it projects
#            the check list from the live union graph; this copy only reads
#            the pack's own ontology.ttl).
#
# KEEP IN SYNC with templates/verify_evidence_sh.tmpl -- same emission
# format, same evidence-pack scaffold; the only intended difference is how
# the check list is obtained (awk over the pack ontology here, SPARQL
# projection at generation time there).
#
# This script ALWAYS exits 0: it records reality, it does not judge it.
set -uo pipefail

# Run from the CONSUMER root (the directory holding ggen.toml).
if [ ! -f ggen.toml ]; then
  echo "verify-evidence-bootstrap.sh: run from the consumer root (no ggen.toml here)" >&2
  exit 2
fi

PACK_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ONTOLOGY="$PACK_DIR/ontology.ttl"

mkdir -p evidence evidence/templates

RECORDED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

GRAPH_HASH="unsynced"
if [ -f .ggen-v2/receipt.json ]; then
  GRAPH_HASH="$(python3 -c 'import json;print(json.load(open(".ggen-v2/receipt.json"))["payload"]["graph_hash"])' 2>/dev/null || echo unsynced)"
fi

# --- project (name, command) pairs from the pack's own ontology -------------
# Blank-line-separated Turtle blocks; keep only ver:RequiredCheck blocks that
# carry both ver:name and ver:checkCommand.
CHECKS_TSV="$(awk 'BEGIN{RS=""; FS="\n"}
  /a ver:RequiredCheck/ {
    name=""; cmd="";
    for (i=1; i<=NF; i++) {
      if ($i ~ /^[ \t]*ver:name[ \t]/ && match($i, /"[^"]*"/))        name=substr($i, RSTART+1, RLENGTH-2);
      if ($i ~ /^[ \t]*ver:checkCommand[ \t]/ && match($i, /"[^"]*"/)) cmd=substr($i, RSTART+1, RLENGTH-2);
    }
    if (name != "" && cmd != "") printf "%s\t%s\n", name, cmd;
  }' "$ONTOLOGY" | LC_ALL=C sort)"

if [ -z "$CHECKS_TSV" ]; then
  echo "verify-evidence-bootstrap.sh: no ver:RequiredCheck with ver:checkCommand found in $ONTOLOGY" >&2
  exit 2
fi

CHECK_NAMES=(); CHECK_CODES=(); CHECK_TOOLS=(); CHECK_SUMMARIES=()
while IFS=$'\t' read -r name cmd; do
  log="${TMPDIR:-/tmp}/verify-evidence-bootstrap-$name-$$.log"
  bash -c "$cmd" >"$log" 2>&1
  code=$?
  CHECK_NAMES+=("$name")
  CHECK_CODES+=("$code")
  CHECK_TOOLS+=("$cmd")
  CHECK_SUMMARIES+=("$(tail -1 "$log" | tr '"' "'" | cut -c1-200)")
  rm -f "$log"
done <<< "$CHECKS_TSV"

# --- scaffold the evidence mini-pack (only if absent) -----------------------
if [ ! -f evidence/pack.toml ]; then
  cat > evidence/pack.toml <<'EOF'
[pack]
name = "verify-evidence"
version = "0.0.0"
description = "GENERATED verification evidence (ver: facts) emitted by scripts/verify-evidence.sh (ggen-verify-pack); admitted into the union graph so ggen-verify-pack's gates can enforce it. Never hand-edited."
EOF
fi
if [ ! -f evidence/templates/evidence_note.md.tmpl ]; then
  cat > evidence/templates/evidence_note.md.tmpl <<'EOF'
---
to: receipts/EVIDENCE_NOTE.md
force: true
---
# Verification evidence admitted

This consumer's `evidence/ontology.ttl` (ver:Check facts with real exit
codes, regenerated by `scripts/verify-evidence.sh`) is part of the union
graph. This file rendering at all means the evidence was admitted and
ggen-verify-pack's gates passed on the last sync.
EOF
fi

# --- emit evidence/ontology.ttl ---------------------------------------------
{
  echo "# GENERATED by verify-evidence-bootstrap.sh at $RECORDED_AT -- do not edit."
  echo "# Real exit codes from real command runs; gated by ggen-verify-pack."
  echo "@prefix ver: <http://seanchatmangpt.github.io/packs/ggen-verify#> ."
  echo
  for i in "${!CHECK_NAMES[@]}"; do
    n="${CHECK_NAMES[$i]}"
    echo "ver:check-$n a ver:Check ;"
    echo "    ver:name \"$n\" ;"
    echo "    ver:tool \"${CHECK_TOOLS[$i]}\" ;"
    echo "    ver:exitCode ${CHECK_CODES[$i]} ;"
    echo "    ver:summary \"${CHECK_SUMMARIES[$i]}\" ;"
    echo "    ver:verifiedGraphHash \"$GRAPH_HASH\" ;"
    echo "    ver:recordedAt \"$RECORDED_AT\" ."
    echo
  done
} > evidence/ontology.ttl

echo "verify-evidence-bootstrap.sh: recorded ${#CHECK_NAMES[@]} checks -> evidence/ontology.ttl (graph hash binding: $GRAPH_HASH)"
for i in "${!CHECK_NAMES[@]}"; do
  echo "  ${CHECK_NAMES[$i]}: exit ${CHECK_CODES[$i]}"
done
exit 0
