//! `Command` bindings for the `fulfillment` embedded
//! workflow — GENERATED by `ggen sync` from the `pddl-embedded-workflow-pack`
//! ontology (`wf:Domain`/`wf:Action` individuals). Do not edit by hand.
//!
//! The real PDDL domain text stays hand-written and owned separately by the
//! application (see `examples/embedded_workflow.rs`'s `DOMAIN` constant).
//! This file lives under `tests/` rather than `examples/` because it is a
//! module of bindings, not a binary — `examples/*.rs` requires `fn main`,
//! `tests/*.rs` does not.

#![cfg(feature = "mfw-planner")]

use bcinr_pddl::prelude::*;
use serde::Serialize;

/// Default adapter routing for one `Command` variant. Generated
/// as a plain, overridable function — not a hard-coded dispatch decision on
/// the command type itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionKind {
    /// Routes through `workflow_cmd::adapters::TaskGroupAdapter` by default.
    Local,
    /// Routes through `workflow_cmd::adapters::OutboxAdapter` by default.
    Durable,
    /// Routes through `workflow_cmd::adapters::ApprovalAdapter` by default.
    HumanApproval,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub enum Command {
    /// `notify-customer` — Notifies the customer once the order is paid; durable so delivery survives a restart.
    NotifyCustomer,
    /// `reserve-inventory` — Reserves inventory once the order is paid.
    ReserveInventory,
}

/// Default execution-kind routing for each generated `Command`
/// variant. Override at the dispatch call site; this is a default, not an
/// authority boundary.
pub fn default_execution_kind(command: &Command) -> ExecutionKind {
    match command {
        Command::NotifyCustomer => ExecutionKind::Durable,
        Command::ReserveInventory => ExecutionKind::Local,
    }
}

#[derive(Debug, Clone, Copy)]
pub struct FulfillmentCommandV1Binding;

impl ActionBinding for FulfillmentCommandV1Binding {
    type Command = Command;
    type Error = String;

    fn binding_name(&self) -> &str {
        "fulfillment-command-v1"
    }

    fn supported_actions(&self) -> Vec<&str> {
        vec![
            "notify-customer",
            "reserve-inventory",
        ]
    }

    fn bind(&self, action: &ActionInvocation) -> Result<Self::Command, Self::Error> {
        match (action.name.as_str(), action.arguments.as_slice()) {
            ("notify-customer", []) => Ok(Self::Command::NotifyCustomer),
            ("reserve-inventory", []) => Ok(Self::Command::ReserveInventory),
            _ => Err(format!("unbound workflow action: {}", action.label)),
        }
    }
}

impl TryFrom<ActionInvocation> for Command {
    type Error = String;

    fn try_from(action: ActionInvocation) -> Result<Self, Self::Error> {
        FulfillmentCommandV1Binding.bind(&action)
    }
}

#[cfg(test)]
mod generated_binding_proof {
    //! Real end-to-end proof, not a hand-transcribed assertion: the real
    //! PDDL domain text below is `examples/embedded_workflow.rs`'s own
    //! `DOMAIN` constant, planned through a real `EmbeddedWorkflow`, and
    //! bound through the generated `FulfillmentCommandV1Binding`
    //! above — proving the ontology's action names/arities actually match
    //! the real domain, not just that the template rendered valid syntax.
    use super::*;
    use std::borrow::Cow;

    const DOMAIN: &str = "(define (domain fulfillment)
  (:requirements :strips)
  (:predicates (paid) (reserved) (customer-notified))
  (:action reserve-inventory
    :parameters ()
    :precondition (paid)
    :effect (reserved))
  (:action notify-customer
    :parameters ()
    :precondition (paid)
    :effect (customer-notified)))";

    struct Order {
        id: u64,
        paid: bool,
    }

    impl WorkflowProblem for Order {
        fn to_pddl_problem(&self) -> Cow<'_, str> {
            let mut problem =
                StripsProblemBuilder::new(format!("order-{}", self.id), "fulfillment")
                    .expect("application identifiers must be valid PDDL symbols");
            if self.paid {
                problem
                    .add_nullary_fact("paid")
                    .expect("domain predicates are compile-time constants");
            }
            problem
                .add_nullary_goal("reserved")
                .expect("domain predicates are compile-time constants")
                .add_nullary_goal("customer-notified")
                .expect("domain predicates are compile-time constants");
            Cow::Owned(
                problem
                    .build()
                    .expect("the application always supplies a goal")
                    .into_string(),
            )
        }
    }

    chicago_tdd_tools::test!(
        generated_binding_matches_the_real_domains_actual_actions,
        {
            let mut workflow =
                EmbeddedWorkflow::new(DOMAIN).expect("embedded planning domain must parse");
            let order = Order { id: 42, paid: true };
            let verified = workflow.plan(&order).expect("workflow should be admitted");
            let registry = BindingRegistry::new(FulfillmentCommandV1Binding)
                .expect("generated binding schema should validate");
            let coverage = registry.coverage(
                verified
                    .batches()
                    .iter()
                    .flat_map(|batch| batch.actions().iter().map(|action| action.name.clone())),
            );
            assert!(
                coverage.is_complete(),
                "generated binding's action set must match the real domain's planned actions: {coverage:?}"
            );
            let commands = verified
                .bind::<Command>()
                .expect("every planner action must have a generated Rust binding");
            for batch in commands.batches() {
                for command in batch.actions() {
                    let _kind = default_execution_kind(command);
                }
            }
        }
    );
}
