PREFIX f5: <https://ggen.dev/ontology/fortune5-required#>
SELECT ?crateName ?path
WHERE {
  ?spec a f5:CargoDependencySpec ;
    f5:dependencyCrateName ?crateName ;
    f5:dependencyPath ?path .
}
ORDER BY ?crateName
