---
to: infra/containers/Dockerfile.verify
sparql:
  row: |
    PREFIX tcps: <http://seanchatmangpt.github.io/packs/tcps-release#>
    SELECT ?body WHERE {
      tcps:DockerfileVerifyArtifact tcps:artifactBody ?body .
    } ORDER BY ?body
---
{{ row[0].body }}
